FLAMEWAKER_Q1_HEALTH_REGEN = 8
FLAMEWAKER_Q1_ARMOR = 15
FLAMEWAKER_Q2_HEAL_PER_TICK_PER_UNIT = 10
FLAMEWAKER_Q2_HEAL_DURATION = 5
FLAMEWAKER_Q3_FLAT_LAVA_DPS = 65
FLAMEWAKER_Q3_STRENGTH_ADDED_TO_LAVA_DMG_PCT = 6
FLAMEWAKER_Q4_BASE_DMG_PER_HP = 0.05
FLAMEWAKER_Q4_BASE_DMG_PER_DAMAGE = 0.01

FLAMEWAKER_W1_DMG_PER_ATT = 0.1
FLAMEWAKER_W2_RANGE = 5
FLAMEWAKER_W2_DAMAGE_BONUS_PCT = 5
FLAMEWAKER_W3_ARMOR_SHRED = -10
FLAMEWAKER_W4_BONUS_DMG_PCT = 40

FLAMEWAKER_E1_DMG = 40
FLAMEWAKER_E2_IMMOLATION_BASE = 30
FLAMEWAKER_E2_IMMOLATION_BONUS_DAMAGE_AGILITY = 10
FLAMEWAKER_E3_BONUS_DMG_PCT = 8
FLAMEWAKER_E3_ATT_SPEED = 10
FLAMEWAKER_E4_CD_REDUCTION = 0.2

FLAMEWAKER_R1_BONUS_ATT_DMG_PCT = 6
FLAMEWAKER_R2_DAMAGE = 25
FLAMEWAKER_R3_STRENGTH = 20
FLAMEWAKER_R4_FIRE_DAMAGE_AMP = 10

FLAMEWAKER_ARCANA_Q_COOLDOWN = 3 -- for prevent interaction with minus cd items in future
FLAMEWAKER_ARCANA_Q_FREE_CAST_DURATION = 0.5
FLAMEWAKER_ARCANA_Q_RADIUS = 360
FLAMEWAKER_ARCANA_Q_MIN_DISTANCE = 200
FLAMEWAKER_ARCANA_Q_MAX_DISTANCE = 1200
FLAMEWAKER_ARCANA_Q1_ARMOR_PER_STACK = 1
FLAMEWAKER_ARCANA_Q1_MANAREGEN_PER_STACK = 1
FLAMEWAKER_ARCANA_Q1_MISSED_HP_FOR_GET_STACK_BASE = 100
FLAMEWAKER_ARCANA_Q1_MAX_STACKS_BASE = 100
FLAMEWAKER_ARCANA_Q2_DURATION = 6
FLAMEWAKER_ARCANA_Q2_MS = 4
FLAMEWAKER_ARCANA_Q2_SPELL_PIERCE = 80
FLAMEWAKER_ARCANA_Q3_PROC_CHANCE = 10
FLAMEWAKER_ARCANA_Q3_DELAY = 0.2
FLAMEWAKER_ARCANA_Q4_DMG_PER_ATT = 0.1
FLAMEWAKER_ARCANA_Q4_ARMOR_AND_SPELL_PIERCE_REDUCTION = -120

FLAMEWAKER_ARCANA2_Q1_FIRE_AMP_AGAINST_STUNNED = 5
FLAMEWAKER_ARCANA2_Q2_HEALTH_REGEN = 40
FLAMEWAKER_ARCANA2_Q2_ARMOR = 50
FLAMEWAKER_ARCANA2_Q3_ATK_POWER_ADDED_TO_FLAME = 1
FLAMEWAKER_ARCANA2_Q3_RANGE = 5
FLAMEWAKER_ARCANA2_Q4_AGILITY_TO_DAMAGE = 0.1

FLAMEWAKER_GLYPH_1_1_RETURN_STUN_CHANCE = 50
FLAMEWAKER_GLYPH_1_1_STUN_DURATION = 1
FLAMEWAKER_GLYPH_2_1_Q_CD = 5
FLAMEWAKER_GLYPH_4_1_ATTIRIBUTES_TO_W_DAMAGE_PER_LVL = 0.1
FLAMEWAKER_GLYPH_4_1_AS_SLOW = 120
FLAMEWAKER_GLYPH_4_1_MS_SLOW = 120
FLAMEWAKER_GLYPH_4_1_SLOW_DURATION = 3
FLAMEWAKER_GLYPH_5_1_R2_DUR_MULTIPLY = 1.5
FLAMEWAKER_GLYPH_6_1_BONUS_ATTACK_DAMAGE = 100
FLAMEWAKER_GLYPH_6_1_DURATION = 7
FLAMEWAKER_GLYPH_7_1_E1_DAMAGE_MULT = 3
FLAMEWAKER_GLYPH_5_A_DAMAGE_CAP = 0.3
FLAMEWAKER_GLYPH_5_A_DAMAGE_CAP_LOW_HP = 0.15
FLAMEWAKER_GLYPH_5_A_LOW_HP_THRESH = 0.5

FLAMEWAKER_IMMORTAL_WEAPON_1_SHIELDS = 50
FLAMEWAKER_IMMORTAL_WEAPON_1_DAMAGE_REDUCTION = 50
FLAMEWAKER_IMMORTAL_WEAPON_1_DURATION = 15

FLAMEWAKER_IMMORTAL_WEAPON_2_ATTACK_DAMAGE_PER_AGILITY = 0.1
FLAMEWAKER_IMMORTAL_WEAPON_2_AGILITY_DURING_E = 1000

FLAMEWAKER_IMMORTAL_WEAPON_3_STUN_DURATION_Q_R_MULT = 2.5