FLAMEWAKER_Q4_BASE_DMG_PER_HP = 0.05
FLAMEWAKER_Q4_BASE_DMG_PER_DAMAGE = 0.001

FLAMEWAKER_W1_DMG_PER_ATT = 0.1
FLAMEWAKER_W3_ARMOR_SHRED = -12
FLAMEWAKER_W4_BONUS_DMG_PCT = 50

FLAMEWAKER_E1_DMG = 600
FLAMEWAKER_E1_PREMIT = 0.001
FLAMEWAKER_E3_BONUS_DMG_PCT = 10
FLAMEWAKER_E3_ATT_SPEED = 12

FLAMEWAKER_R1_BONUS_ATT_DMG_PCT = 25
FLAMEWAKER_R2_INNER_SCALE_BASE = 0.1
FLAMEWAKER_R2_DMG_EXP_SCALE_BASE = 4
FLAMEWAKER_R2_SCALE = 0.5
FLAMEWAKER_R2_INSTANCE_OF_DAMAGE_COUNT = 7

FLAMEWAKER_ARCANA_Q_COOLDOWN = 3 -- for prevent interaction with minus cd items in future
FLAMEWAKER_ARCANA_Q_FREE_CAST_DURATION = 0.5
FLAMEWAKER_ARCANA_Q_RADIUS = 360
FLAMEWAKER_ARCANA_Q_MIN_DISTANCE = 200
FLAMEWAKER_ARCANA_Q_MAX_DISTANCE = 1200
FLAMEWAKER_ARCANA_Q1_ARMOR_PER_STACK = 0.4
FLAMEWAKER_ARCANA_Q1_MANAREGEN_PER_STACK = 2
FLAMEWAKER_ARCANA_Q1_MISSED_HP_FOR_GET_STACK_BASE = 200
FLAMEWAKER_ARCANA_Q1_MAX_STACKS_BASE = 500
FLAMEWAKER_ARCANA_Q2_DURATION = 6
FLAMEWAKER_ARCANA_Q3_PROC_CHANCE = 10
FLAMEWAKER_ARCANA_Q3_DELAY = 0.2
FLAMEWAKER_ARCANA_Q4_DMG_PER_ATT = 2

FLAMEWAKER_GLYPH_1_1_RETURN_STUN_CHANCE = 50
FLAMEWAKER_GLYPH_1_1_STUN_DURATION = 1
FLAMEWAKER_GLYPH_2_1_Q_CD = 5
FLAMEWAKER_GLYPH_4_1_ATTIRIBUTES_TO_W_DAMAGE_PER_LVL = 5
FLAMEWAKER_GLYPH_4_1_ATTACK_DAMAGE_TO_W_DAMAGE_PCT_PER_LVL = 20
FLAMEWAKER_GLYPH_4_1_AS_SLOW = 120
FLAMEWAKER_GLYPH_4_1_MS_SLOW = 120
FLAMEWAKER_GLYPH_4_1_SLOW_DURATION = 3
FLAMEWAKER_GLYPH_5_1_R2_DUR_MULTIPLY = 1.5
FLAMEWAKER_GLYPH_6_1_BONUS_ATTACK_DAMAGE = 100
FLAMEWAKER_GLYPH_6_1_DURATION = 7
FLAMEWAKER_GLYPH_7_1_E1_DAMAGE_MULT = 3
FLAMEWAKER_GLYPH_5_A_DAMAGE_CAP = 0.3
FLAMEWAKER_GLYPH_5_A_DAMAGE_CAP_LOW_HP = 0.15
FLAMEWAKER_GLYPH_5_A_LOW_HP_THRESH = 0.5

FLAMEWAKER_IMMORTAL_WEAPON_1_SHIELDS = 50
FLAMEWAKER_IMMORTAL_WEAPON_1_DAMAGE_REDUCTION = 90
FLAMEWAKER_IMMORTAL_WEAPON_1_DURATION = 15

FLAMEWAKER_IMMORTAL_WEAPON_2_ATTACK_DAMAGE_PER_AGILITY = 6
FLAMEWAKER_IMMORTAL_WEAPON_2_AGILITY_DURING_E = 50000

FLAMEWAKER_IMMORTAL_WEAPON_3_STUN_DURATION_Q_R_MULT = 2.5