local prefix = 'items/lua/foot/'
require(prefix..'storm_pacer_sabatons')
require(prefix..'redfall_runners')
require(prefix..'dunetreads')
require(prefix..'iron_treads_of_destruction')
require(prefix..'boots_of_the_violet_guard')
require(prefix..'emerald_speed_runners')
require(prefix..'swamp_waders')
require(prefix..'voyager_boots')
require(prefix..'bloodstone_boots')
require(prefix..'hangman_slippers')
require(prefix.."boots_of_temperance")
require(prefix.."gravewalkers")
