local prefix = 'items/lua/helm/'
require(prefix..'arcane_cascade_hat')
require(prefix..'helm_of_the_iron_colossus')
require(prefix..'hood_of_lords')
require(prefix..'twisted_blue_mask_of_ahnqhir')
require(prefix..'twisted_purple_mask_of_ahnqhir')
require(prefix..'twisted_yellow_mask_of_ahnqhir')
require(prefix..'veil_of_the_cerulean_high_guard')
require(prefix..'mask_of_the_phantom_sorcerer')
require(prefix..'shadowguard_helm')
require(prefix..'sun_gods_visage')