CHERNOBOG_SHADOWS_ATT_INTERVAL_BASE = 0.45
CHERNOBOG_SHADOWS_INTERVALS_FOR_ATT = 3

CHERNOBOG_Q1_EXTRA_POSTMIT_PCT = 2
CHERNOBOG_Q2_INTERVAL_THINK = 0.5
CHERNOBOG_Q2_PER_LVL = 700
CHERNOBOG_Q3_ATT_AMP_PERCENT = 15
CHERNOBOG_Q4_BUFF_Q2_INTERVAL_THINK = 0.04
CHERNOBOG_Q4_RANGE = 15
CHERNOBOG_Q4_WIDTH = 10
CHERNOBOG_Q4_CD_REDUCTION_TIMES = 0.04


CHERNOBOG_W_RADIUS = 100
CHERNOBOG_W1_RADIUS = 100
CHERNBOG_W1_DMG_PER_MISSING_MP = 10
CHERNOBOG_W1_HEAL = 500
CHERNOBOG_W3_STACK_LOSE_PCT = 40

CHERNOBOG_E_ATTACK_TELEPORTATION_CD = 0.6
CHERNOBOG_E_MOVE_TELEPORTATION_CD = 1.5
CHERNOBOG_E1_MOVESPEED = 1
CHERNOBOG_E1_ATT_PCT = 6
CHERNOBOG_E2_RADIUS = 300
CHERNOBOG_E3_CD_BASE = 0.4
CHERNOBOG_E3_DISTANCE = 12
CHERNOBOG_E3_POSTMIT = 0.05
CHERNOBOG_E3_POSTMIT_DUR_BASE = 1
CHERNOBOG_E4_BASE_DUR = 0.7
CHERNOGBOG_E4_DUR = 0.2

CHERNOBOG_R1_AMP_PCT = 7
CHERNOBOG_R2_DMG_PER_ATT = 0.6
CHERNOBOG_R3_DMG_PER_ATT = 0.5
CHERNOBOG_R4_CLAW_RANGE_BASE =500
CHERNOBOG_R4_CLAW_RANGE = 50

CHERNOBOG_ARCANA_R1_DAMAGE_PCT = 2
CHERNOBOG_ARCANA_R2_ATT_SLOW = -2
CHERNOBOG_ARCANA_R2_MS_SLOW = -4
CHERNOBOG_ARCANA_R3_SPLIT_PCT = 15
CHERNOBOG_ARCANA_R4_DURATION_INC = 0.5
CHERNOBOG_ARCANA_R4_POST_MITI_PCT = 10

CHERNOBOG_ARCANA_E1_CLAMP_BASE = 600
CHERNOBOG_ARCANA_E1_CLAMP = 4
CHERNOBOG_ARCANA_E1_STACKS_CHANCE = 5
CHERNOBOG_ARCANA_E2_BONUS_DAMAGE_PCT = 10
CHERNOBOG_ARCANA2_E_EVA_PCT = 100
CHERNOBOG_ARCANA2_E3_ATT_PER_DEMON_PCT = 4
CHERNOBOG_ARCANA2_E4_MS = 5
CHERNOBOG_ARCANA2_E3_MS_CAP = 5

CHERNOBOG_T31_CD_DEC = 0.5
CHERNOBOG_GLYPH11_SHADOWS_INTERVALS_FOR_ATT = 1
CHERNOBOG_GLYPH_4_1_RADIUS = 250
CHERNOBOG_T51_DRAIN_HP_CAP_PCT = 0.5
CHERNOBOG_T51_DRAIN_MP_CAP_PCT = 0.5
CHERNOBOG_T51_BAD_MULT_EXCEPT_E = 0.8
CHERNOBOG_GLYPH61_RADIUS = 500
