CHERNOBOG_SHADOWS_ATT_INTERVAL_BASE = 0.3
CHERNOBOG_SHADOWS_INTERVALS_FOR_ATT = 3

CHERNOBOG_Q1_AMP = 3.5
CHERNOBOG_Q2_DMG = 7000
CHERNOBOG_Q2_DEMON_AMP_PCT = 5
CHERNOBOG_Q3_BONUS_ATTACK_DMG = 15
CHERNOBOG_Q4_DEMON_AMP_PCT = 0.1
CHERNOBOG_Q4_ADD_BASE_DAMAGE = 0.1

CHERNOBOG_W1_HEAL = 500
CHERNOBOG_W1_DAMAGE_PER_MANA_SPENT = 100
CHERNOBOG_W2_ARMOR = 200
CHERNOBOG_W2_BASE_DAMAGE = 3600
CHERNOBOG_W3_ARMOR_RED = -15
CHERNOBOG_W3_BASE_DAMAGE_STACK = 200
CHERNOBOG_W4_BONUS_STR = 450
CHERNOBOG_W4_BONUS_AGI = 450

CHERNOBOG_E1_ATT_PCT = 6
CHERNOBOG_E2_ILLUSION_DAMAGE_PCT = 50
CHERNOBOG_E2_ARMOR = 50
CHERNOBOG_E3_BASE_RANGE = 400
CHERNOBOG_E3_RANGE = 12
CHERNOBOG_E3_CD_BASE = 0.4
CHERNOBOG_E3_POSTMIT = 0.05
CHERNOBOG_E3_POSTMIT_DUR_BASE = 1
CHERNOBOG_E4_EVASION_LINGER_BASE = 0.7
CHERNOBOG_E4_EVASION_LINGER = 0.2

CHERNOBOG_R1_AMP_PCT = 7
CHERNOBOG_R2_DMG_PER_ATT = 0.6
CHERNOBOG_R3_DMG_PER_ATT = 0.5
CHERNOBOG_R4_CLAW_RANGE_BASE =500
CHERNOBOG_R4_CLAW_RANGE = 50

CHERNOBOG_ARCANA_R1_DAMAGE_PCT = 2
CHERNOBOG_ARCANA_R2_ATT_SLOW = -2
CHERNOBOG_ARCANA_R2_MS_SLOW = -4
CHERNOBOG_ARCANA_R3_SPLIT_PCT = 15
CHERNOBOG_ARCANA_R4_DURATION_INC = 0.5
CHERNOBOG_ARCANA_R4_POST_MITI_PCT = 10

CHERNOBOG_ARCANA2_E_EVA_PCT = 100
CHERNOBOG_ARCANA2_E3_ATT_PER_DEMON_PCT = 4
CHERNOBOG_ARCANA2_E4_MS = 5
CHERNOBOG_ARCANA2_E3_MS_CAP = 5

CHERNOBOG_GLYPH11_SHADOWS_INTERVALS_FOR_ATT = 1
CHERNOBOG_GLYPH51_DRAIN_HP_CAP_PCT = 0.5
CHERNOBOG_GLYPH51_BAD_MULT_EXCEPT_E = 0.5
CHERNOBOG_GLYPH61_RADIUS = 500
