CHERNOBOG_SHADOWS_ATT_INTERVAL_BASE = 0.3
CHERNOBOG_SHADOWS_INTERVALS_FOR_ATT = 3

CHERNOBOG_E1_ATT_PCT = 6
CHERNOBOG_E3_CD_BASE = 0.4
CHERNOBOG_E3_POSTMIT = 0.05
CHERNOBOG_E3_POSTMIT_DUR_BASE = 1

CHERNOBOG_R2_DMG_PER_ATT = 0.6
CHERNOBOG_R3_DMG_PER_ATT = 0.5

CHERNOBOG_ARCANA2_E_EVA_PCT = 100
CHERNOBOG_ARCANA2_E3_ATT_PER_DEMON_PCT = 4
CHERNOBOG_ARCANA2_E4_MS = 5
CHERNOBOG_ARCANA2_E3_MS_CAP = 5

CHERNOBOG_GLYPH11_SHADOWS_INTERVALS_FOR_ATT = 1
CHERNOBOG_GLYPH51_DRAIN_HP_CAP_PCT = 0.5
CHERNOBOG_GLYPH51_BAD_MULT_EXCEPT_E = 0.5
CHERNOBOG_GLYPH61_RADIUS = 500



