TRAPPER_Q_TRAP_RADIUS = 420
TRAPPER_Q1_DAMAGE = 2500
TRAPPER_Q1_MAX_STACKS_COUNT = 10
TRAPPER_Q2_DAMAGE = 50000
TRAPPER_Q3_AMP_PERCENT = 15 
TRAPPER_Q4_DAMAGE_AMP_PER_INT_PCT = 0.2

TRAPPER_W_BOMBS_COUNT = 3
TRAPPER_W_RADIUS = 500
TRAPPER_W1_AMP_PERCENT = 4
TRAPPER_W2_DURATION_BASE = 10
TRAPPER_W2_DAMAGE = 100
TRAPPER_W3_PROC_CHANCE = 3
TRAPPER_W3_AMP_INVISIBLE_W = 0.1
TRAPPER_W3_DMG_PROC = 0.8
TRAPPER_W3_DELAY = 1
TRAPPER_W4_AMPLIFY_PERCENT = 0.5

TRAPPER_E1_BONUS_DAMAGE = 30
TRAPPER_E2_DECOY_DURATION = 10
TRAPPER_E2_DECOY_HEALTH = 10
TRAPPER_E2_STATS_DAMAGE = 900
TRAPPER_E2_EXPLODE_RADIUS = 550
TRAPPER_E3_DAMAGE_PERCENT = 36
TRAPPER_E3_ATTACK_RANGE = 4
TRAPPER_E4_POST_AMP_PERCENT = 15

TRAPPER_R1_RADIUS = 650
TRAPPER_R1_DMG_PCT_NEAREST = 0.5 --?????
TRAPPER_R1_DMG_TARGET_MORE_TIMES_BASE = 10 --???
TRAPPER_R2_DURATION = 5
TRAPPER_R2_MAX_STACKS_COUNT = 10
TRAPPER_R2_ATTACK_DAMAGE = 1000
TRAPPER_R3_CRIT_DAMAGE = 45
TRAPPER_R3_DURATION = 9
TRAPPER_R4_BONUS_AGI = 1000

TRAPPER_ARCANA_W_W1_POST_AMP_PERCENT = 1.2
TRAPPER_ARCANA_W_W1_MAX_STACKS = 50
TRAPPER_ARCANA_W_W2_NORMAL_PCT = 0.15
TRAPPER_ARCANA_W_W3_AGI_DAMAGE = 350
TRAPPER_ARCANA_W_W4_ELEMENTAL_AMP_PER_ATTRIBUTE_PCT = 0.03

TRAPPER_GLYPH_2_1_HEAL_PCT = 3
TRAPPER_GLYPH_3_1_ADD_BOMBS = 2
TRAPPER_GLYPH_3_1_ADD_RADIUS = 200
TRAPPER_GLYPH_3_1_SHIELDS = 3
TRAPPER_GLYPH_5_1_DISTANCE = 1400
TRAPPER_GLYPH_5_1_SEARCH_DISTANCE = 600
TRAPPER_GLYPH_5_1_COOLDOWN = 2
TRAPPER_GLYPH_5_1_INVISIBLE_W_DURATION_AMPLIFY = 1.5
TRAPPER_GLYPH_5_1_INVISIBLE_W_RADIUS_AMPLIFY = 2
TRAPPER_GLYPH_6_1_NORMAL_ITEM_AMPLIFY = 4
TRAPPER_GLYPH_5_A_POISON_STACKS = 15
TRAPPER_GLYPH_5_A_FULMINATING_AMP = 1.5
TRAPPER_GLYPH_5_A_TORRENT_DUR_UNTIL = 1
TRAPPER_GLYPH_5_A_NET_DUR_AMP = 2

TRAPPER_GLYPH_3_1_RADIUS = 550
TRAPPER_GLYPH_5_1_RADIUS_AMPLIFY_PERCENT = 10
TRAPPER_GLYPH_5_1_MAX_STACKS_COUNT = 10
TRAPPER_GLYPH_6_1_NORMAL_AMPLIFY_DECREASE_PERCENT = 30 --don't affect filters

T12_AMPLIFY = 2
TRAPPER_T32_DAMAGE_RED = 0.9
TRAPPER_T32_DURATION = 5
T52_STACKS_COUNT = 10
T62_DECOY_HEALTH = 1
T62_DECOY_DAMAGE_AMPLIFY_PERCENT = 200

T5A_DAMAGE_AMPLIFY = 7

TRAPPER_IMMORTAL_WEAPON_2_DAMAGE_AMP_PCT = 30

TRAPPER_IMMORTAL_WEAPON_3_RANGE = 600
TRAPPER_IMMORTAL_WEAPON_3_CD_RED = 0.65