SEINARU_Q_STUN_DUR_BASE = 0.3
SEINARU_Q_BLIND_DUR_BASE = 4
SEINARU_Q1_ATT_PCT_PER_STACK = 0.0005
SEINARU_Q1_ATT_SPD_PER_STACK = 0.3
SEINARU_Q1_DUR_BASE = 10
SEINARU_Q2_MOV_SPD = 3
SEINARU_Q2_MOV_SLOW = 2
SEINARU_Q2_DUR_BASE = 5.5
SEINARU_Q3_ARMOR_AND_SPELL_PIERCE_PER_MS = 0.1
SEINARU_Q3_BUFF_DURATION = 6
SEINARU_Q4_ADD_DMG_PER_ATT = 0.15

SEINARU_W1_DAMAGE = 15
SEINARU_W1_RANGE_BASE = 140
SEINARU_W1_RANGE_PER_LVL = 8
SEINARU_W1_MOV_SLOW_BASE = 60
SEINARU_W1_DUR_BASE = 2.5
SEINARU_W2_MAGIC_ARMOR_LOSS_DURATION = 9
SEINARU_W2_CHANCE = 20
SEINARU_W2_DMG = 90
SEINARU_W2_RADIUS_BASE = 420
SEINARU_W2_MAGIC_ARMOR_LOSS = -50
SEINARU_W3_DUR_BASE = 6
SEINARU_W3_SHIELD_PER_AGI = 0.5
SEINARU_W4_SPIRIT = 25
SEINARU_W4_WIND_AMP = 0.1

SEINARU_E1_ATT_PCT = 8
SEINARU_E1_TARGETS_BASE = 1
SEINARU_E1_TARGETS = 1
SEINARU_E2_CHANCE = 16
SEINARU_E3_ARMOR_PIERCE = 60
SEINARU_E4_HOLY_AMP = 0.1
SEINARU_E4_AGILITY = 50

SEINARU_R_CAST_END_HIT_MULT = 3
SEINARU_R1_ARMOR_RED = 40
SEINARU_R2_DMG_RED = 0.5
SEINARU_R2_DUR_BASE = 8
SEINARU_R2_DUR = 0.1
SEINARU_R2_RADIUS_BASE = 500
SEINARU_R2_RADIUS = 5
SEINARU_R3_DMG_PER_ATT = 0.002
SEINARU_R3_DMG_BASE = 5
SEINARU_R4_STRENGTH = 75

SEINARU_ARCANA_Q1_CRIT_CHANCE = 30
SEINARU_ARCANA_Q1_CRIT_DMG = 0.05
SEINARU_ARCANA_Q2_ATT_PCT_PER_STACK = 1
SEINARU_ARCANA_Q2_MAX_STACKS = 3
SEINARU_ARCANA_Q3_AGI = 60
SEINARU_ARCANA_Q4_EVA_BASE = 100
SEINARU_ARCANA_Q4_DUR = 0.25

SEINARU_ARCANA_E1_ATT_PCT = 4
SEINARU_ARCANA_E1_TARGETS = 0.5
SEINARU_ARCANA_E2_PURE_DMG_REDUCE = 0.9
SEINARU_ARCANA_E2_DUR = 0.1
SEINARU_ARCANA_E3_ARMOR_PIERCE_AND_SPELL_PIERCE = 110
SEINARU_ARCANA_E4_HOLY_PCT = 3
SEINARU_ARCANA2_E4_HOLY_AMP = 12

SEINARU_GLYPH1_LIFESTEAL = 0.02
SEINARU_GLYPH2_MOVESPEED_CAP_PER_Q2 = 1.2
SEINARU_GLYPH3_R3_RADIUS = 255
SEINARU_GLYPH_4_1_MS = 120
SEINARU_GLYPH5_W_DMG_AMP_VS_BLINDED = 2
SEINARU_GLYPH6_R2_DMG_RED = 0.65
SEINARU_GLYPH_7_1_ARMOR_PIERCE_AND_MAGIC_ARMOR_PER_STR = 1

SEINARU_WEAP_1_DMG_PER_ATT = 0.2
SEINARU_WEAP_1_RADIUS = 250
