SERENGAARD_MITHRIL_NEVERLORD = 1000
SERENGAARD_MITHRIL_RAZORMORE = 1200
SERENGAARD_MITHRIL_DEMON = 1400

SERENGAARD_MITHRIL_MULT_NORMAL = 1
SERENGAARD_MITHRIL_MULT_ELITE = 2
SERENGAARD_MITHRIL_MULT_LEGEND = 3

SERENGAARD_MITHRIL_INF_BASE = 500
SERENGAARD_MITHRIL_INF_PER_WAVE = 70
SERENGAARD_MITHRIL_INF_PER_WAVE_MAX = 3300