SERENGAARD_MITHRIL_NEVERLORD = 60
SERENGAARD_MITHRIL_RAZORMORE = 100
SERENGAARD_MITHRIL_DEMON = 120

SERENGAARD_MITHRIL_MULT_NORMAL = 2
SERENGAARD_MITHRIL_MULT_ELITE = 4
SERENGAARD_MITHRIL_MULT_LEGEND = 12

SERENGAARD_MITHRIL_INF_BASE = 140
SERENGAARD_MITHRIL_INF_PER_WAVE = 10
SERENGAARD_MITHRIL_INF_PER_WAVE_MAX = 400