SERENGAARD_MITHRIL_NEVERLORD = 600
SERENGAARD_MITHRIL_RAZORMORE = 900
SERENGAARD_MITHRIL_DEMON = 1200

SERENGAARD_MITHRIL_MULT_NORMAL = 1
SERENGAARD_MITHRIL_MULT_ELITE = 2
SERENGAARD_MITHRIL_MULT_LEGEND = 3

SERENGAARD_MITHRIL_INF_BASE = 500
SERENGAARD_MITHRIL_INF_PER_WAVE = 50
SERENGAARD_MITHRIL_INF_PER_WAVE_MAX = 2500