DUSKBRINGER_Q_BASE_RADIUS = 280
DUSKBRINGER_Q1_DMG_PER_STACK = 6
DUSKBRINGER_Q1_DURATION = 5
DUSKBRINGER_Q1_MAX_STACKS = 50
DUSKBRINGER_Q2_ITEM_PCT = 0.05
DUSKBRINGER_Q3_ADD_DMG_PCT_MAX = 0.05
DUSKBRINGER_Q4_ADD_RADIUS = 12
DUSKBRINGER_Q4_ADD_DMG_PCT = 0.05

DUSKBRINGER_W1_DMG_PER_ATT = 0.005
DUSKBRINGER_W1_BASE_DMG = 8
DUSKBRINGER_W2_MAG_RES_RED = -32
DUSKBRINGER_W3_HEAL = 20
DUSKBRINGER_W4_ROOTED_DAMAGE_BLOCK_PCT = 4

DUSKBRINGER_E1_ATT_DMG = 20
DUSKBRINGER_E1_ARMOR = 50
DUSKBRINGER_E1_BASE_DUR = 1
DUSKBRINGER_E2_BASE_DUR = 0.7
DUSKBRINGER_E2_DUR = 0.2
DUSKBRINGER_E3_PROC_CHANCE = 4
DUSKBRINGER_E4_BASE_RADIUS = 900
DUSKBRINGER_E4_DUR = 0.2

DUSKBRINGER_R1_DMG_PER_DMG = 0.04
DUSKBRINGER_R1_BASE_RADIUS = 700
DUSKBRINGER_R2_BASE_DUR = 7
DUSKBRINGER_R2_PIERCES = 9
DUSKBRINGER_R2_MAX_STACKS = 7
DUSKBRINGER_R3_ATT_DMG_PCT = 2
DUSKBRINGER_R3_BASE_DUR = 6
DUSKBRINGER_R4_GHOST_AMP = 0.1

DUSKBRINGER_ARCANA_W1_ADD_DMG_PER_ATT_PER_LEVEL = 0.02
DUSKBRINGER_ARCANA_W2_BASE_DUR = 6
DUSKBRINGER_ARCANA1_W2_ARMORS = 50
DUSKBRINGER_ARCANA_W3_PROC_CHANCE = 10
DUSKBRINGER_ARCANA_W4_BASE_DUR = 18
DUSKBRINGER_ARCANA_W4_ATT_FLAT = 100
DUSKBRINGER_ARCANA_W4_ATT_PCT = 4

DUSKBRINGER_GLYPH_1_1_ = 0
DUSKBRINGER_GLYPH_2_1_STACKS_PER_SEC = 3
DUSKBRINGER_GLYPH_3_1_INCR_DUR = 1
DUSKBRINGER_GLYPH_4_1_ = 0
DUSKBRINGER_GLYPH_5_1_INCR_ATTS = 7
DUSKBRINGER_GLYPH_6_1_CD = 4
DUSKBRINGER_GLYPH_7_1_MULT_STACKS = 2
DUSKBRINGER_GLYPH_5_a_CD = 22

DUSKBRINGER_GLYPH_1_2_BASE_DUR = 20
DUSKBRINGER_GLYPH_1_2_HPREG = 10
DUSKBRINGER_GLYPH_2_2_Q1_STACKS = 3
DUSKBRINGER_GLYPH_3_2_TICK_TIME_DECR = 50
DUSKBRINGER_GLYPH_3_2_DMG_DECR = 0.4
DUSKBRINGER_GLYPH_4_2_RES_PER_STACK = 0.03
DUSKBRINGER_GLYPH_4_2_MAX_STACKS = 25
DUSKBRINGER_GLYPH_5_2_BASE_RADIUS = 250
DUSKBRINGER_GLYPH_6_2_CLEANCE_INTERVAL = 0.3
DUSKBRINGER_GLYPH_7_2_ = 0

DUSKBRINGER_Q1_ARCANA2_DMG_PER_STACK = 15

DUSKBRINGER_Q2_ARCANA2_DURATION_PER_LV = 0.06
DUSKBRINGER_Q3_ARCANA2_DURATION_INCREASE = 0.03
DUSKBRINGER_ARCANA2_Q4_SPELL_PIERCE = 120
DUSKBRINGER_ARCANA2_Q4_ATTACK_POWER_PCT = 2.5
DUSKBRINGER_Q4_DURATION_AFTER = 4

DUSKBRINGER_IMMORTAL_WEAPON_1_DUSKFIRE_STACK_MULT = 2

DUSKBRINGER_IMMORTAL_WEAPON_2_W_STUN = 0.8

DUSKBRINGER_IMMORTAL_WEAPON_3_BASH_CHANCE = 25
DUSKBRINGER_IMMORTAL_WEAPON_3_BASH_DURATION = 2
DUSKBRINGER_IMMORTAL_WEAPON_3_E2_SHIELD_STACKS_PER_BASH = 5
