BAHAMUT_Q_BASE_DURATION = 8

BAHAMUT_Q1_MANA_PER_TICK = 1
BAHAMUT_Q1_SELF_TICK_INTERVAL = 0.05
BAHAMUT_Q1_MANAPOOL_PER_STACK = 1
BAHAMUT_Q1_MANAPOOL_STACKS_PER_TICK = 60
BAHAMUT_Q1_MANAPOOL_STACKS_DURATION = 20
BAHAMUT_Q2_ATTACK_RANGE = 15 --broken in gems branch for some reason, requires check
BAHAMUT_Q3_MS_SLOW = 12
BAHAMUT_Q4_INT_BONUS = 70

BAHAMUT_W1_BONUS_DMG_AND_BAD_PCT = 0.5
BAHAMUT_W2_DAMAGE_PCT = 1
BAHAMUT_W2_RADIUS = 700
BAHAMUT_W3_BASE_DMG = 20
BAHAMUT_W3_DMG = 40
BAHAMUT_W3_ATTACK_TO_DMG_PCT = 0.5
BAHAMUT_W4_ATT_PER_MANA = 0.02

BAHAMUT_E1_CHANCE = 1
BAHAMUT_E2_DAMAGE = 30
BAHAMUT_E2_PARALYZE_DURATION = 0.05
BAHAMUT_E3_DAMAGE = 70
BAHAMUT_E3_BASE_DAMAGE = 40
BAHAMUT_E3_ARMOR_MULT = 20
BAHAMUT_E4_HOLY_AMP = 0.1

BAHAMUT_R1_ATTACKSPEED = 15
BAHAMUT_R1_MOVESPEED = 10
BAHAMUT_R1_DURATION = 12
BAHAMUT_R2_BASE_DAMAGE_PCT = 20
BAHAMUT_R2_DAMAGE_PCT = 10
BAHAMUT_R2_SPELL_PIERCE = 40
BAHAMUT_R2_PIERCE_DURATION = 8
BAHAMUT_R3_MS_SLOW = 10
BAHAMUT_R3_AS_SLOW = 8
BAHAMUT_R4_TICK_RATE = 0.1
BAHAMUT_R4_STATS_PER_TICK = 0.5
BAHAMUT_R4_DURATION = 9

BAHAMUT_ARCANA_R_RADIUS = 750
BAHAMUT_ARCANA_R_SLOW = 65
BAHAMUT_ARCANA_R_DURATION = 16
BAHAMUT_ARCANA_R_TICK_RATE = 0.1
BAHAMUT_ARCANA_R_R1_DMG_OF_W_PCT = 5
BAHAMUT_ARCANA_R2_PIERCES = 35
BAHAMUT_ARCANA_R_R3_ATTRIBUTES_TO_DMG = 0.01
BAHAMUT_ARCANA_R_R4_ADD_BOLTS_CHANCE = 10

BAHAMUT_ARCANA_W_BASE_SPEED = 1188
BAHAMUT_ARCANA_W_W1_LIFESTEAL_PCT = 0.1
BAHAMUT_ARCANA_W_W1_DMG_DIVISOR = 100
BAHAMUT_ARCANA_W_W1_OVERHEAL_TO_ALLIES_PCT = 10
BAHAMUT_ARCANA_W_W1_OVERHEAL_RADIUS = 500
BAHAMUT_ARCANA_W_W2_SPELL_PIERCE = 40
BAHAMUT_ARCANA_W_W2_DURATION = 8
BAHAMUT_ARCANA_W_W3_PARALYSIS = 0.02
BAHAMUT_ARCANA_W_W4_ATK_DMG_PER_MISSING_MANA = 0.04
BAHAMUT_ARCANA_W_W4_R_SPEED_MULT = 2

BAHAMUT_GLYPH_1_1_PHYS_RES_PCT  = 30
BAHAMUT_GLYPH_2_1 = 0	
BAHAMUT_GLYPH_3_1_W_RADIUS_INCREASE_PCT = 30
BAHAMUT_GLYPH_4_1_Q_DURATION = 2
BAHAMUT_GLYPH_5_1_R4_DURATION = 3
BAHAMUT_GLYPH_6_1_E3_STUN = 1.5
BAHAMUT_GLYPH_6_1_PULSES = 5
BAHAMUT_GLYPH_7_1_E3_RADIUS_INCREASE_PCT = 40
BAHAMUT_GLYPH_5_A_FREE_Q_INTERVAL = 4

BAHAMUT_IMMORTAL_WEAPON_1_CHANCE = 20
BAHAMUT_IMMORTAL_WEAPON_1_DAMAGE_AMP = 2

BAHAMUT_IMMORTAL_WEAPON_2_MOVESPEED_BONUS_PCT = 25
BAHAMUT_IMMORTAL_WEAPON_2_BASE_E_CD = 4.5

BAHAMUT_IMMORTAL_WEAPON_3_Q_LENGHT_INCREASE_PCT = 100
BAHAMUT_IMMORTAL_WEAPON_3_Q_DAMAGE_INCREASE_PCT = 100
