VOLTEX_Q2_BAD_FLAT_PER_AGI = 1

VOLTEX_W1_DMG_PER_ATT_PER_LVL = 0.1
VOLTEX_R2_CHANCE = 30
VOLTEX_R2_DMG_PER_ATT_BASE = 8
VOLTEX_R2_DMG_PER_ATT = 1.5

VOLTEX_ARCANA1_E1_DMG_PER_ATT = 0.6
VOLTEX_ARCANA1_E2_DMG_PER_ATT = 0.6