VOLTEX_Q1_ARMOR = 100
VOLTEX_Q2_BASE_LIGHTNING_DMG_PER_AGI = 1
VOLTEX_Q3_ARMOR_LOSS_PER_STACK = 4
VOLTEX_Q3_DMG_PER_ATT = 0.5
VOLTEX_Q4_ADD_DMG_PER_ATT = 0.15

VOLTEX_W3_DMG_PER_AGI = 5

VOLTEX_5_A_DURATION_INCREASE_PCT = 100