local prefix = 'items/lua/body/'
require(prefix..'armor_of_atlantis')
require(prefix..'armor_of_the_violet_guard')
require(prefix..'enchanted_solar_cape')
require(prefix..'plate_of_the_watcher')
require(prefix..'dark_arts_vestments')
require(prefix..'musty_crypt_armor')
require(prefix..'spellcrafter_coat')
require(prefix..'cloak_of_isolation')
require(prefix..'breastplate_of_abjudication')
require(prefix..'gold_plate_of_leon')
require(prefix..'legion_vestments')