TANARI_MITHRIL_NORMAL_MULT = 1
TANARI_MITHRIL_ELITE_MULT = 2
TANARI_MITHRIL_LEGEND_MULT = 3
TANARI_MITHRIL_SPIRIT_REALM_MULT = 1.5

TANARI_MITHRIL_WIND = 800
TANARI_MITHRIL_WATER = 880
TANARI_MITHRIL_FIRE = 960

TANARI_MITHRIL_SPIRIT_WIND = 1040
TANARI_MITHRIL_SPIRIT_WATER = 1040
TANARI_MITHRIL_SPIRIT_FIRE = 1040

TANARI_MITHRIL_ANCIENT_GOD = 1440
TANARI_MITHRIL_ANCIENT_GOD_PARAGON_MULT = 4