TANARI_MITHRIL_NORMAL_MULT = 1
TANARI_MITHRIL_ELITE_MULT = 2
TANARI_MITHRIL_LEGEND_MULT = 6
TANARI_MITHRIL_SPIRIT_REALM_MULT = 3

TANARI_MITHRIL_WIND = 30
TANARI_MITHRIL_WATER = 70
TANARI_MITHRIL_FIRE = 100

TANARI_MITHRIL_SPIRIT_WIND = 160
TANARI_MITHRIL_SPIRIT_WATER = 160
TANARI_MITHRIL_SPIRIT_FIRE = 160

TANARI_MITHRIL_ANCIENT_GOD = 300
TANARI_MITHRIL_ANCIENT_GOD_PARAGON_MULT = 2