WARLORD_FIRE_CHARGE_ELEMENT_BONUS_PCT = 6
WARLORD_ICE_CHARGE_ELEMENT_BONUS_PCT = 6
WARLORD_EARTH_CHARGE_ELEMENT_BONUS_PCT = 6

WARLORD_Q1_HP_REGEN = 300
WARLORD_Q2_ARMOR_INCR_PCT = 9
WARLORD_Q3_ARMOR_RED = 15
WARLORD_Q3_DUR_BASE = 12
WARLORD_Q4_ALL_ATTRIBUTES = 900
WARLORD_Q4_DUR_BASE = 20

WARLORD_W1_RADIUS_BASE = 240
WARLORD_W1_RADIUS = 4
WARLORD_W1_STUN_DUR = 0.05
WARLORD_W2_FREEZE_DUR_BASE = 1
WARLORD_W2_FREEZE_DUR = 0.1
WARLORD_W2_INCR_PHYS_AND_MAG_DMG_TAKEN_PCT = 7
WARLORD_W2_IMMUNITY_DUR = 4
WARLORD_W3_RADIUS_INCR = 5
WARLORD_W3_DMG_BONUS_PER_BASEATT = 0.4
WARLORD_W4_DMG_BONUS_PER_DMG = 0.025
WARLORD_W4_DMG_BONUS_PER_BASEATT = 0.2

WARLORD_E1_MAX_EARTH_CHARGES = 1
WARLORD_E1_ARMOR_PER_EARTH_CHARGE = 5
WARLORD_E2_MANA_RESTORE = 150
WARLORD_E2_INTERVAL_BASE = 0.1
WARLORD_E2_W_BONUS_DMG_PCT = 100
WARLORD_E3_DMG_BASE = 10000
WARLORD_E3_DMG = 15400
WARLORD_E3_TARGETS_BASE = 3
WARLORD_E3_TARGETS = 1
WARLORD_E4_ICE_EARTH_FIRE_BONUS_PER_ATTR = 0.00005 --0.05% per 10 attributes

WARLORD_R1_HEAL_PER_R_HEAL = 0.015
WARLORD_R1_DMG_PER_BASE_ATT = 0.03
WARLORD_R2_POST_MIT_PCT = 5
WARLORD_R3_ATT_DMG_BONUS_PER_FIRE_CHARGE_PCT = 1
WARLORD_R4_ATT_DMG_BONUS_PER_CHARGE = 740

WARLORD_ARCANA2_Q1_POST_MIT = 5
WARLORD_ARCANA2_Q2_DURATION_BASE = 0.5
WARLORD_ARCANA2_Q2_DURATION_PER_LEVEL = 0.15
WARLORD_ARCANA2_Q2_INT_BONUS = 300
WARLORD_ARCANA2_Q2_DAMAGE_REDUCTION_PCT = 96
WARLORD_ARCANA2_Q3_GREEN_DMG_PCT = 30
WARLORD_ARCANA2_Q3_ATK_SPEED = 20
WARLORD_ARCANA2_Q4_ALL_ATTRIBUTES = 500
WARLORD_ARCANA2_Q4_DRAGON_AMP_PER_ATTRIBUTES = 0.003

WARLORD_GLYPH_5_1_DURATION = 9
WARLORD_GLYPH_5_1_MAX_STACKS = 50
WARLORD_GLYPH_5_1_BONUS_ATTACK_DMG_PER_KILL = 4
WARLORD_GLYPH_6_1_ADDITIONAL_CHARGES = 5
WARLORD_GLYPH_7_1_MAGICAL_SPLASH_PCT = 800
WARLORD_GLYPH_7_1_MAGICAL_SPLASH_AOE = 460
WARLORD_GLYPH_5_A_FIRE_CHARGES_PER_DMG_TAKEN = 2
WARLORD_GLYPH_5_A_POST_MITI_PER_ICE_CHARGE_PCT = 5

WARLORD_IMMORTAL_WEAPON_1_STACK_MULT = 2
WARLORD_IMMORTAL_WEAPON_3_INTERVAL = 1
WARLORD_IMMORTAL_WEAPON_3_CHARGES_PER_TICK = 1