WARLORD_ARCANA2_Q1_POST_MIT = 5
WARLORD_ARCANA2_Q2_DURATION_BASE = 0.5
WARLORD_ARCANA2_Q2_DURATION_PER_LEVEL = 0.15
WARLORD_ARCANA2_Q2_INT_BONUS = 300
WARLORD_ARCANA2_Q2_DAMAGE_REDUCTION_PCT = 96
WARLORD_ARCANA2_Q3_GREEN_DMG_PCT = 30
WARLORD_ARCANA2_Q3_ATK_SPEED = 20
WARLORD_ARCANA2_Q4_ALL_ATTRIBUTES = 500
WARLORD_ARCANA2_Q4_DRAGON_AMP_PER_ATTRIBUTES = 0.003

WARLORD_GLYPH_5_1_DURATION = 9
WARLORD_GLYPH_5_1_MAX_STACKS = 50
WARLORD_GLYPH_5_1_BONUS_ATTACK_DMG_PER_KILL = 4
WARLORD_GLYPH_6_1_ADDITIONAL_CHARGES = 5
WARLORD_GLYPH_7_1_MAGICAL_SPLASH_PCT = 100
WARLORD_GLYPH_7_1_MAGICAL_SPLASH_AOE = 320
WARLORD_GLYPH_5_A_FIRE_CHARGES_PER_DMG_TAKEN = 2
WARLORD_GLYPH_5_A_POST_MITI_PER_ICE_CHARGE_PCT = 5