WARLORD_FIRE_CHARGE_ELEMENT_BONUS_PCT = 2
WARLORD_ICE_CHARGE_ELEMENT_BONUS_PCT = 2
WARLORD_EARTH_CHARGE_ELEMENT_BONUS_PCT = 2

WARLORD_Q1_HP_REGEN = 15
WARLORD_Q2_ARMOR = 45
WARLORD_Q3_ARMOR_RED = -10
WARLORD_Q3_DUR_BASE = 12
WARLORD_Q4_ALL_ATTRIBUTES = 60
WARLORD_Q4_DUR_BASE = 20

WARLORD_W1_RADIUS_BASE = 240
WARLORD_W1_RADIUS = 4
WARLORD_W1_STUN_DUR = 0.05
WARLORD_W2_FREEZE_DUR_BASE = 1
WARLORD_W2_FREEZE_DUR = 0.15
WARLORD_W2_IMMUNITY_DUR = 4
WARLORD_W3_RADIUS_INCR = 5
WARLORD_W3_DMG_BONUS_PER_BASEATT = 0.01
WARLORD_W4_DMG_BONUS_PER_DMG = 0.025
WARLORD_W4_DMG_BONUS_PER_BASEATT = 0.002

WARLORD_E1_MAGIC_ARMOR_PER_EARTH_CHARGE = 2
WARLORD_E2_MANA_RESTORE = 10
WARLORD_E2_INTERVAL_BASE = 0.1
WARLORD_E2_W_BONUS_DMG_PCT = 10
WARLORD_E3_DMG_BASE = 30
WARLORD_E3_DMG = 80
WARLORD_E3_TARGETS_BASE = 3
WARLORD_E3_TARGETS = 1
WARLORD_E4_ICE_EARTH_FIRE_BONUS = 0.05

WARLORD_R1_HEAL_PER_R_HEAL = 0.01
WARLORD_R1_DMG_PER_CHARGE = 10
WARLORD_R2_MAGIC_ARMOR_REDUCTION = -50
WARLORD_R3_ATT_DMG_BONUS_PER_FIRE_CHARGE_PCT = 0.02
WARLORD_R4_ATT_DMG_BONUS_PER_CHARGE = 3

WARLORD_ARCANA1_DMG_PCT = 0.003
WARLORD_ARCANA1_R2_DMG_PER_ATTRIBUTES = 0.05
WARLORD_ARCANA1_R2_THRESHOLD = 0.3
WARLORD_ARCANA1_R2_BOSS_THRESHOLD = 0.15
WARLORD_ARCANA1_R2_THRESHOLD_MULTIPLIER = 200
WARLORD_ARCANA1_R3_DMG_PCT_MAX_HEALTH = 0.005
WARLORD_ARCANA1_R4_ENHANCED_CHARGES = 1
WARLORD_ARCANA1_R4_ATK_PER_FIRE_CHARGE = 0.1

WARLORD_ARCANA2_Q1_PIERCES = 60
WARLORD_ARCANA2_Q2_DURATION_BASE = 0.5
WARLORD_ARCANA2_Q2_DURATION_PER_LEVEL = 0.15
WARLORD_ARCANA2_Q2_INT_BONUS = 15
WARLORD_ARCANA2_Q2_DAMAGE_REDUCTION_PCT = 50
WARLORD_ARCANA2_Q3_GREEN_DMG_PCT = 2
WARLORD_ARCANA2_Q3_ATK_SPEED = 12
WARLORD_ARCANA2_Q4_ALL_ATTRIBUTES = 200
WARLORD_ARCANA2_Q4_DRAGON_AMP = 0.2

WARLORD_GLYPH_5_1_DURATION = 9
WARLORD_GLYPH_5_1_MAX_STACKS = 50
WARLORD_GLYPH_5_1_BONUS_ATTACK_DMG_PER_KILL = 1
WARLORD_GLYPH_6_1_ADDITIONAL_CHARGES = 5
WARLORD_GLYPH_7_1_MAGICAL_SPLASH_PCT = 30
WARLORD_GLYPH_7_1_MAGICAL_SPLASH_AOE = 460
WARLORD_GLYPH_5_A_FIRE_CHARGES_PER_DMG_TAKEN = 2
WARLORD_GLYPH_5_A_SPELL_PIERCE_PER_ICE_CHARGE = 40

WARLORD_IMMORTAL_WEAPON_1_STACK_MULT = 2
WARLORD_IMMORTAL_WEAPON_3_INTERVAL = 1
WARLORD_IMMORTAL_WEAPON_3_CHARGES_PER_TICK = 1