--BASIC
CONJUROR_Q_CAST_RANGE = 500
CONJUROR_Q1_ASPECT_HP_BONUS_PCT = 5
CONJUROR_Q1_ARMOR_AURA = 15
CONJUROR_Q2_CLAP_DAMAGE_OF_ASPECT_HP_PCT = 2
CONJUROR_Q2_RADIUS = 360
CONJUROR_Q2_CHANCE = 15
CONJUROR_Q3_HP_REGEN = 25
CONJUROR_Q4_EARTH_AND_FIRE_AMP = 0.1

CONJUROR_W1_DMG_BASE = 10
CONJUROR_W1_DMG = 25
CONJUROR_W1_HEALTH_GAIN_PCT = 0.01
CONJUROR_W2_BONUS_DMG_PCT = 1
CONJUROR_W2_ARMOR_REDUCTION = 18
CONJUROR_W3_CRIT_DMG_PCT = 45
CONJUROR_W4_HEALTH_DAMAGE_PER_TICK = 5
CONJUROR_W4_AMP_ON_FIRE = 15

CONJUROR_E1_BONUS_DMG_PCT = 0.01
CONJUROR_E1_BONUS_AGI = 1
CONJUROR_E2_DAMAGE = 80
CONJUROR_E2_BASE_DAMAGE = 20
CONJUROR_E2_ADDITIONAL_DAMAGE_PER_AGI = 0.05
CONJUROR_E3_STATS_TO_ATTACK_DAMAGE_PCT = 1.5
CONJUROR_E3_BONUS_ATTACK_RANGE = 12
CONJUROR_E4_ATTACK_PURE_PCT = 2
CONJUROR_E4_E2_PURE_PCT = 3

CONJUROR_R_DURATION_BASE = 20
CONJUROR_R1_Q_AMP_PCT = 12
CONJUROR_R1_STUN = 0.1
CONJUROR_R1_RADIUS = 600
CONJUROR_R2_BONUS_DMG_PCT = 3
CONJUROR_R2_ARMOR_SHRED = -90
CONJUROR_R2_BONUS_ATTACK_RANGE = 500
CONJUROR_R3_AS_REDUCTION = 8
CONJUROR_R3_MS_REDUCTION = 8
CONJUROR_R4_R_DUR_INCREASE = 0.6

CONJUROR_ARCANA3_GRAND_GUARDIAN_ARMOR = 50000
CONJUROR_ARCANA_Q1_DMG_PERCENT_MAX_HEALTH = 2
CONJUROR_ARCANA_Q1_RADIUS_BASE = 500
CONJUROR_ARCANA_Q1_RADIUS_SCALE = 5
CONJUROR_ARCANA_Q2_FLAT_HEALTH = 75
CONJUROR_ARCANA_Q2_PERCENT_HEALTH = 0.5
CONJUROR_ARCANA_Q3_EARTH_AMP_FOR_100_MAX_HEALTH = 0.01
CONJUROR_ARCANA_Q3_ATTACK_DMG_TO_EARTH_SHOCK_PCT = 1.5
CONJUROR_ARCANA_Q4_DAMAGE_REDUCE_PCT = 1.2

CONJUROR_ARCANA_W1_ATTACK_PCT_FROM_INT = 0.01
CONJUROR_ARCANA_W1_BASE_ATTACK_FROM_BUFF = 40
CONJUROR_ARCANA_W2_FLAT_FIRE_AMP = 5
CONJUROR_ARCANA_W2_DAMAGE_BONUS_W_PCT = 1
CONJUROR_ARCANA_W3_CRIT_DMG_PCT = 10
CONJUROR_ARCANA_W4_AGI_AND_INT_PCT = 2
CONJUROR_ARCANA_W4_STR_PCT = -1

CONJUROR_ARCANA_E1_ATTACK_POWER_BLACK_RAZOR = 0.2
CONJUROR_ARCANA_E1_ATTACK_POWER_BONUS_PCT = 3
CONJUROR_ARCANA_E2_SHADOW_DAMAGE_INSTANCES = 1
CONJUROR_ARCANA_E3_SHADOW_AMP = 3
CONJUROR_ARCANA_E3_AGILITY_GEAR_AMP = 3
CONJUROR_ARCANA_E4_SPLIT_CHANCE = 20

CONJUROR_ARCANA_R1_DAMAGE_SPLASH_PCT = 4
CONJUROR_ARCANA_R2_DAMAGE_PER_ATTACK_PCT = 0.5
CONJUROR_ARCANA_R2_STUN = 0.05
CONJUROR_ARCANA_R3_STACK_CHANCE = 5
CONJUROR_ARCANA_R4_DURATION = 0.5

CONJUROR_GLYPH_1_1_FIRE_ASPECT_BONUS_AS = 100
CONJUROR_GLYPH_1_1_FIRE_ASPECT_BONUS_ATTACK_DMG_PCT = 100	
CONJUROR_GLYPH_2_1_BONUS_ASPECTS_HP_PCT = 60
CONJUROR_GLYPH_3_1_E_CD_DURING_R = 4
CONJUROR_GLYPH_4_1_SHADOW_ASPECT_BONUS_ATTACK_RANGE = 420
CONJUROR_GLYPH_5_1_Q_BONUS_RADIUS = 80
CONJUROR_GLYPH_5_1_FREE_CAST_DURATION_INCREASE = 1.5
CONJUROR_GLYPH_6_1_CRIT = 5
CONJUROR_GLYPH_5_A_ARMOR_AND_SPELL_PIERCE = 1200

CONJUROR_IMMORTAL_WEAPON_2_BAD_PER_ATTRIBUTES_PCT = 0.1