CONJUROR_W1_ARCANA_ATTACK_PCT_FROM_INT = 0.2
CONJUROR_W1_BASE_ATTACK_FROM_BUFF = 10000

CONJUROR_ARCANA_W2_FLAT_FIRE_AMP = 50
CONJUROR_ARCANA_W2_DAMAGE_BONUS_W_PCT = 100

CONJUROR_ARCANA_W4_AGI_AND_INT_PCT = 3
CONJUROR_ARCANA_W4_STR_PCT = -1.5