CONJUROR_W1_ARCANA_ATTACK_PCT_FROM_INT = 0.2
CONJUROR_W1_BASE_ATTACK_FROM_BUFF = 10000

CONJUROR_ARCANA_W2_FLAT_FIRE_AMP = 50
CONJUROR_ARCANA_W2_DAMAGE_BONUS_W_PCT = 100

CONJUROR_ARCANA_W4_AGI_AND_INT_PCT = 3
CONJUROR_ARCANA_W4_STR_PCT = -1.5

CONJUROR_ARCANA_Q1_DMG_PERCENT_MAX_HEALTH = 60
CONJUROR_ARCANA_Q1_RADIUS_BASE = 500
CONJUROR_ARCANA_Q1_RADIUS_SCALE = 5

CONJUROR_ARCANA_Q2_FLAT_HEALTH = 1800
CONJUROR_ARCANA_Q2_PERCENT_HEALTH = 4

CONJUROR_ARCANA_Q3_EARTH_AMP_FOR_100_MAX_HEALTH = 0.01
CONJUROR_ARCANA_Q3_ATTACK_DMG_TO_EARTH_SHOCK_PCT = 100

CONJUROR_ARCANA_Q4_DAMAGE_REDUCE_PCT = 1.2

CONJUROR_ARCANA_E1_ATTACK_POWER_BLACK_RAZOR = 15
CONJUROR_ARCANA_E1_ATTACK_POWER_BONUS_PCT = 10

CONJUROR_ARCANA_E2_SHADOW_INSTANCE = 10

CONJUROR_ARCANA_E3_SHADOW_AMP = 0.1
CONJUROR_ARCANA_E3_AGILITY_GEAR_AMP = 4

CONJUROR_ARCANA_E4_SPLIT_CHANCE = 10