VENOMORT_BOSSES_COUNT_AS_ENEMIES = 20
VENOMORT_PARAGONS_COUNT_AS_ENEMIES = 5

VENOMORT_Q_TICK_RATE = 0.4
VENOMORT_Q_DEBUFF_DURATION = 8
VENOMORT_Q_RANGE = 800
VENOMORT_Q1_BAD_PER_ENEMY_PERCENT = 0.1
VENOMORT_Q1_MAX_STACKS = 50
VENOMORT_Q1_DURATION = 20
VENOMORT_Q2_DAMAGE_PER_INT = 0.05
VENOMORT_Q3_ATTACK_SPEED_SLOW = 6
VENOMORT_Q4_RANGE = 10

VENOMORT_W_DURATION = 3
VENOMORT_W1_DAMAGE_PER_HP_PERCENT = 10
VENOMORT_W2_DURATION = 0.07
VENOMORT_W2_IMMUNE_DURATION = 7
VENOMORT_W2_TICK_RATE = 0.3
VENOMORT_W2_CHANCE = 40
VENOMORT_W3_BONUS_ATTRIBUTES = 0.3
VENOMORT_W4_POSTMIT_PER_HP_PERCENT = 0.75

VENOMORT_E1_POISON_AMPLIFY_PERCENT = 2
VENONORT_E2_DURATION = 5
VENOMORT_E2_TICK_RATE = 0.1
VENOMORT_E2_DAMAGE_PER_LEVEL = 30
VENOMORT_E3_DURATION = 1
VENOMORT_E3_RADIUS = 900
VENOMORT_E3_TICK_RATE = 0.6
VENOMORT_E3_AURA_DAMAGE_PERCENT = 2
VENOMORT_E4_HP_PER_ENEMY = 50
VENOMORT_E4_EVASION_PER_ENEMY = 0.15
VENOMORT_E4_DURATION = 1.5
VENOMORT_E4_MAX_STACKS = 50
VENOMORT_E4_TICK_RATE = 0.8
VENOMORT_E4_DELAY = 0.2

VENOMORT_R_DURATION = 16
VENOMORT_R_ATTACK_SPEED = 100
VENOMORT_R1_VIPER_DAMAGE_PERCENT = 20
VENOMORT_R2_VIPER_SCALE_PERCENT = 3
VENOMORT_R3_STACKS = 1
VENOMORT_R3_DURATION = 5
VENOMORT_R3_DAMAGE_REDUCTION_PERCENT = 1
VENOMORT_R4_ADD_HP = 200
VENOMORT_R4_ADD_DAMAGE = 75

VENOMORT_ARCANA1_R_RADIUS = 600
VENOMORT_ARCANA_1_R_BASE_MOVESPEED = 100
VENOMORT_ARCANA_1_R1_DURATION = 3
VENOMORT_ARCANA_1_R1_DAMAGE_PERCENT = 12
VENOMORT_ARCANA_1_R2_RADIUS = 5
VENOMORT_ARCANA_1_R2_INSTANCES_FOR_R1 = 1
VENOMORT_ARCANA_1_R3_HEAL_PERCENT = 0.03
VENOMORT_ARCANA_1_R3_SHIELD_PERCENT = 5
VENOMORT_ARCANA_1_R4_BONUS_MOVESPEED = 8
VENOMORT_ARCANA_1_R4_ARMOR_BONUS = 135

VENOMORT_ARCANA2_Q1_DAMAGE = 40
VENOMORT_ARCANA2_Q1_DAMAGE_PER_HERO_LVL_BASE = 0
VENOMORT_ARCANA2_Q2_SPEED_BURST = 0.3
VENOMORT_ARCANA2_Q2_SPEED_BURST_BASE = 30
VENOMORT_ARCANA2_Q2_SEARCH_RADIUS = 6
VENOMORT_ARCANA2_Q3_MAX_STACKS_COUNT = 15
VENOMORT_ARCANA2_Q3_DURATION = 10
VENOMORT_ARCANA2_Q3_DOT_AMPLIFY_PERCENT = 1.5
VENOMORT_ARCANA2_Q4_ADD_CHANCE_PERCENT = 5
VENOMORT_ARCANA2_Q4_BAD_PERCENT = 0.5

VENOMORT_GLYPH_1_1_COOLDOWN = 1.5
VENOMORT_GLYPH_2_1_BOSSES_COUNT_AS_ENEMIES = 30
VENOMORT_GLYPH_2_1_PARAGONS_COUNT_AS_ENEMIES = 8
VENOMORT_GLYPH_3_1_HEAL_PERCENT = 15
VENOMORT_GLYPH_3_1_E_CD_RED = 2
VENOMORT_GLYPH_3_1_E_CAST_RANGE_AMP = 2
VENOMORT_GLYPH_5_1_AMPLIFY_W3 = 2
VENOMORT_GLYPH_6_1_DAMAGE_REDUCTION_PERCENT = 30
VENOMORT_GLYPH_6_1_DURATION = 15
VENOMORT_GLYPH_7_1_ADDITIONAL_LIFETIME = 10
VENOMORT_GLYPH_7_1_ADDITIONAL_ATTACK_SPEED = 80

VENOMORT_GLYPH_1_2_DURATION_INCREASE_PERCENT = 40
VENOMORT_GLYPH_2_2_RADIUS = 500
VENOMORT_GLYPH_3_2_HEALTH_THRESHOLD_PERCENT = 10
VENOMORT_GLYPH_3_2_AMPLIFY = 10
VENOMORT_GLYPH_4_2_DURATION = 9
VENOMORT_GLYPH_5_2_RANGE_INCREASE_PERCENT = 100
VENOMORT_GLYPH_7_2_HEALTH_THRESHOLD_PERCENT = 95
VENOMORT_GLYPH_7_2_POSTMITIGATION_PERCENT = 200

VENOMORT_IMMORTAL_WEAPON_1_AOE_RADIUS = 300
VENOMORT_IMMORTAL_WEAPON_2_FUSIONS_COUNT = 5
VENOMORT_IMMORTAL_WEAPON_3_E2_DAMAGE_PER_RUNE_FROM_HP_PERCENT = 100
