SORCERESS_Q1_BASE_DAMAGE = 40
SORCERESS_Q1_ADD_DAMAGE = 30
SORCERESS_Q1_ICE_LANCE_PROJECTILE = "particles/econ/items/mirana/mirana_crescent_arrow/sorceress_ice_lance.vpcf"
SORCERESS_Q2_FROST_NOVA_DAMAGE = 120
SORCERESS_Q2_BASE_DURATION = 1
SORCERESS_Q2_ADD_DURATION = 0.04
SORCERESS_Q3_CHANCE = 15
SORCERESS_Q3_AMPLIFY_PERCENT = 4
SORCERESS_Q3_BASE_DURATION = 0.5
SORCERESS_Q3_ADD_DURATION = 0.05
SORCERESS_Q3_RADIUS = 450
SORCERESS_Q3_IMMUNE_DURATION = 8
SORCERESS_Q3_TIME_BEFORE_IMMUNE = 5
SORCERESS_Q4_ICE_AMP = 10

SORCERESS_W1_DMG_INT_MULT = 0.1
SORCERESS_W1_START_DURATION = 1.2
SORCERESS_W1_ADD_DURATION = 0.1
SORCERESS_W2_DURATION = 4
SORCERESS_W2_MAX_STACKS_COUNT = 5
SORCERESS_W2_MAGIC_ARMOR_LOSS = -25
SORCERESS_W3_RADIUS = 1600
SORCERESS_W3_MANA_REGEN = 4
SORCERESS_W3_INTELLECT = 4
SORCERESS_W4_AMPLIFY_PERCENT = 10

SORCERESS_E_CLEAR_CAST_DURATION = 3
SORCERESS_E1_STACKS = 2
SORCERESS_E1_STACKS_SPEND = 10
SORCERESS_E2_BASE_DAMAGE = 10
SORCERESS_E2_ARMOR_AMPLIFY = 2
SORCERESS_E2_HEALTH_AMPLIFY = 2
SORCERESS_E2_ADD_DAMAGE = 40
SORCERESS_E3_AMPLIFY_PERCENT = 10
SORCERESS_E4_DAMAGE_AS_PCT_OF_ELEMENTAL_ATK_POWER = 10

SORCERESS_R1_BASE_DAMAGE = 60
SORCERESS_R1_ADD_DAMAGE = 80
SORCERESS_R1_MAX_STACKS_COUNT = 3
SORCERESS_R3_DURATION = 6
SORCERESS_R4_FIRE_AMP = 0.1

SORCERESS_ARCANA1_R2_START_DURATION = 1
SORCERESS_ARCANA1_R2_ADD_DURATION = 0.04
SORCERESS_ARCANA1_R2_CRIT_DAMAGE = 15
SORCERESS_ARCANA1_R2_CHANCE = 15
SORCERESS_ARCANA1_R2_IMMUNE_DURATION = 8
SORCERESS_ARCANA1_R3_ICE_RESIST_LOSS = 0.003

SORCERESS_ARCANA2_Q1_BASE_DMG_PER_LEVEL = 80
SORCERESS_ARCANA2_Q1_BASE_DMG = 100
SORCERESS_ARCANA2_Q1_ATT_TO_DMG_PCT = 3
SORCERESS_ARCANA2_Q2_DAMAGE = 200
SORCERESS_ARCANA2_Q2_COOLDOWN = 8
SORCERESS_ARCANA2_Q2_AMP_IN_RING = 4
SORCERESS_ARCANA2_Q3_DAMAGE_PCT = 0.2
SORCERESS_ARCANA2_Q4_FIRE_AMP = 15

SORCERESS_GLYPH_1_1_Q_DAMAGE_MULT = 1.5
SORCERESS_GLYPH_1_1_MS_SLOW = 100
SORCERESS_GLYPH_1_1_AS_SLOW = 100
SORCERESS_GLYPH_2_1_Q1_ADDITIONAL_PROJECTILES = 2
SORCERESS_GLYPH_3_1_ADDITIONAL_FIREBALLS = 4
SORCERESS_GLYPH_4_1_BONUS_AS = 210
SORCERESS_GLYPH_4_1_BONUS_AS_ELEMENTAL = 300
SORCERESS_GLYPH_4_1_W1_SHIELDS = 4
SORCERESS_GLYPH_5_1_AMPLIFY = 2
SORCERESS_GLYPH_5_1_RADIUS = 1200
SORCERESS_GLYPH_5_1_INTERVAL = 0.2
SORCERESS_GLYPH_7_1_R_DAMAGE_MULTIPLIER = 1.5

SORCERESS_GLYPH_5_A_MULTIPLY = 5

SORCERESS_GLYPH_1_2_CHANCE = 15
SORCERESS_GLYPH_1_2_DURATION = 1
SORCERESS_GLYPH_2_2_CHANCE = 40
SORCERESS_GLYPH_2_2_DAMAGE_AMPLIFY = 1.5
SORCERESS_GLYPH_3_2_BONUS_AMPLIFY = 2
SORCERESS_GLYPH_4_2_STACKS_SPEND = 7
SORCERESS_GLYPH_5_2_STUN_IMMUNITY_COUNTER_REDUCTION = 0.5
SORCERESS_GLYPH_6_2_R3_MULT = 2
SORCERESS_GLYPH_7_2_DAMAGE_AMPLIFY = 2.5
SORCERESS_GLYPH_7_2_MANA_DRAIN_PERCENT = 1