SPIRIT_WARRIOR_W_DAMAGE_REDUCTION = 0.3

SPIRIT_WARRIOR_Q1_BASE = 0
SPIRIT_WARRIOR_Q1_DMG = 4
SPIRIT_WARRIOR_Q1_MAX_STACKS = 30
SPIRIT_WARRIOR_Q1_BURN_DURATION = 6
SPIRIT_WARRIOR_Q1_ARMOR_DEBUFF = -4
SPIRIT_WARRIOR_Q2_FIRE_SHIELD_ARMORS = 20
SPIRIT_WARRIOR_Q2_EVASION = 0.5
SPIRIT_WARRIOR_Q3_DMG_PCT = 1
SPIRIT_WARRIOR_Q4_FIRE_AND_WIND_AMP = 0.08

SPIRIT_WARRIOR_W1_BASE_DMG_PER_MANA = 0.01
SPIRIT_WARRIOR_W2_BASE_DMG = 15
SPIRIT_WARRIOR_W2_DURATION = 5
SPIRIT_WARRIOR_W2_MAX_STACKS = 3
SPIRIT_WARRIOR_W3_ATTACK_POWER_TO_DMG_PCT = 0.1
SPIRIT_WARRIOR_W3_Q_MULT_PCT = 1
SPIRIT_WARRIOR_W4_DMG_INCR_PCT = 30
SPIRIT_WARRIOR_W4_STUN = 0.2

SPIRIT_WARRIOR_E1_DMG = 35
SPIRIT_WARRIOR_E1_BONUS_WINDSRIKE_PCT = 0.5
SPIRIT_WARRIOR_E2_ARMOR_AURA = 10
SPIRIT_WARRIOR_E3_DPS = 35
SPIRIT_WARRIOR_E3_DURATION_BASE = 4
SPIRIT_WARRIOR_E3_DAMAGE_REDUCTION = 0.5
SPIRIT_WARRIOR_E3_DURATION = 0.15
SPIRIT_WARRIOR_E4_SPIRIT_AND_INT = 35

SPIRIT_WARRIOR_R1_LIFESTEAL_PCT = 0.1
SPIRIT_WARRIOR_R1_DURATION = 5
SPIRIT_WARRIOR_R2_BONUS_DMG_PCT = 1
SPIRIT_WARRIOR_R3_ATTACK_POWER_TO_DAMAGE = 1
SPIRIT_WARRIOR_R4_AS_BOOST = 22

SPIRIT_WARRIOR_ARCANA_W1_BASE_DMG_PER_HP = 0.12
SPIRIT_WARRIOR_ARCANA_W1_BONUS_HP = 2000
SPIRIT_WARRIOR_ARCANA_W2_PCT = 4
SPIRIT_WARRIOR_ARCANA_W3_MULTIPLE_THROW_CHANCE = 10
SPIRIT_WARRIOR_ARCANA_W4_FIRE_AMP_PER_ATTRIBUTE = 0.08

SPIRIT_WARRIOR_ARCANA_E1_DMG = 8800
SPIRIT_WARRIOR_ARCANA_E3_DPS = 12000
SPIRIT_WARRIOR_ARCANA_E3_DURATION_BASE = 3
SPIRIT_WARRIOR_ARCANA_E3_DURATION = 0.12
SPIRIT_WARRIOR_ARCANA_E4_WIND_AMP_PER_ATTRIBUTE = 0.08

SPIRIT_WARRIOR_ARCANA_R1_HEAL_PCT = 0.3
SPIRIT_WARRIOR_ARCANA_R2_ATTACK_POWER_TO_DMG_PCT = 35
SPIRIT_WARRIOR_ARCANA_R2_RADIUS = 200
SPIRIT_WARRIOR_ARCANA_R3_CURR_HP_TO_DMG_PCT = 60
SPIRIT_WARRIOR_ARCANA_R3_POST_MITI_PCT = 3
SPIRIT_WARRIOR_ARCANA_R4_WATER_AMP_PER_ATTRIBUTE = 0.08

SPIRIT_WARRIOR_GLYPH_1_1_E_JUMP_SPEED_INCREASE_PCT = 50
SPIRIT_WARRIOR_GLYPH_3_1_MAX_SPIRITS = 5
SPIRIT_WARRIOR_GLYPH_4_1_E1_REPEATS = 4
SPIRIT_WARRIOR_GLYPH_4_1_E1_REPEAT_INTERVAL = 0.75
SPIRIT_WARRIOR_GLYPH_5_1_W_HIT_MANACOST_PCT_RESTORE = 15
SPIRIT_WARRIOR_GLYPH_7_1_ADDITIONAL_DURATION = 40
SPIRIT_WARRIOR_GLYPH_5_A_STACK_INTERVAL = 0.5
SPIRIT_WARRIOR_GLYPH_5_A_AS_PER_STACK = 25
SPIRIT_WARRIOR_GLYPH_5_A_BONUS_DMG_PER_STACK_PCT = 15
SPIRIT_WARRIOR_GLYPH_5_A_ATTACK_RANGE_PER_STACK = 15

SPIRIT_WARRIOR_IMMORTAL_WEAPON_1_Q_DURATION_BONUS = 10
SPIRIT_WARRIOR_IMMORTAL_WEAPON_1_Q_DAMAGE_AMP_PCT = 100

SPIRIT_WARRIOR_IMMORTAL_WEAPON_3_SPLITSHOT_ENEMIES = 2