RUBILASH_ILLUSION_CAST_DELAY = 0.5
RUBILASH_PAINTED_DURATION_BASE = 9

RUBILASH_ALL_COLORS = {"red", "blue", "yellow", "green", "purple", "orange", "black"}

RUBILASH_MULTS = {}
RUBILASH_MULTS["red"] = {}
RUBILASH_MULTS["blue"] = {}
RUBILASH_MULTS["yellow"] = {}

RUBILASH_MULTS["red"]["red"] = 2
RUBILASH_MULTS["red"]["orange"] = 4
RUBILASH_MULTS["red"]["purple"] = 4
RUBILASH_MULTS["red"]["black"] = 8

RUBILASH_MULTS["yellow"]["yellow"] = 2
RUBILASH_MULTS["yellow"]["orange"] = 4
RUBILASH_MULTS["yellow"]["green"] = 4
RUBILASH_MULTS["yellow"]["black"] = 8

RUBILASH_MULTS["blue"]["blue"] = 2
RUBILASH_MULTS["blue"]["purple"] = 4
RUBILASH_MULTS["blue"]["green"] = 4
RUBILASH_MULTS["blue"]["black"] = 8

RUBILASH_TEXT_COLOR_RED = "#FF0000"
RUBILASH_TEXT_COLOR_YELLOW = "#FFFF00"
RUBILASH_TEXT_COLOR_BLUE = "#0000FF"
RUBILASH_TEXT_COLOR_ORANGE = "#FF8800"
RUBILASH_TEXT_COLOR_PURPLE = "#AA00DD"
RUBILASH_TEXT_COLOR_GREEN = "#00FF00"
RUBILASH_TEXT_COLOR_BLACK = "#000000"
RUBILASH_TEXT_COLOR_WHITE = "#FFFFFF"

RUBILASH_RUNE_Q1_CAST_RANGE = 10
RUBILASH_RUNE_Q2_ARMOR_AND_MAGIC_ARMOR_LOSS = -70
RUBILASH_RUNE_Q3_FEAR_DURATION = 0.12
RUBILASH_RUNE_Q3_FEAR_DURATION_BASE = 0.6
RUBILASH_RUNE_Q4_DEMON_AND_GHOST_AMP = 8

RUBILASH_RUNE_W1_EXTRA_PAINT_DURATION = 0.1
RUBILASH_RUNE_W2_ARMOR_PIERCE_AND_MAGIC_ARMOR_LOSS = -70
RUBILASH_RUNE_W3_ATTACK_SPEED = 15
RUBILASH_RUNE_W3_W_AMP = 5
RUBILASH_RUNE_W4_SLOW = -9

RUBILASH_RUNE_E1_MANA_RESTORE = 100
RUBILASH_RUNE_E1_ATTACK_PER_MANA = 0.01
RUBILASH_RUNE_E2_SPELL_PIERCE_AND_MAGIC_ARMOR_LOSS = -70
RUBILASH_RUNE_E3_PAINT_HEAL_PCT = 1
RUBILASH_RUNE_E4_HEALTH_PER_ATTR = 0.8




RUBILASH_GLYPH_1_1_PROJECTILE_SPEED_PCT = 150
RUBILASH_GLYPH_2_1_Q_BAD = 100
RUBILASH_GLYPH_3_1_RANGE = 300
RUBILASH_GLYPH_3_1_INTERVAL = 2
RUBILASH_GLYPH_4_1_MAGIC_ARMOR = 5000
RUBILASH_GLYPH_6_1_DAMAGE_INCREASE_PCT = 400
RUBILASH_GLYPH_7_1_DAMAGE_REDUCE_PCT = -50
RUBILASH_GLYPH_5_A_ATTACK_POWER_BONUS = 400