RUBILASH_ILLUSION_CAST_DELAY = 0.5
RUBILASH_PAINTED_DURATION_BASE = 9

RUBILASH_ALL_COLORS = {"red", "blue", "yellow", "green", "purple", "orange", "black"}

RUBILASH_MULTS = {}
RUBILASH_MULTS["red"] = {}
RUBILASH_MULTS["blue"] = {}
RUBILASH_MULTS["yellow"] = {}
RUBILASH_MULTS["white"] = {}

RUBILASH_MULTS["red"]["red"] = 2
RUBILASH_MULTS["red"]["orange"] = 4
RUBILASH_MULTS["red"]["purple"] = 4
RUBILASH_MULTS["red"]["black"] = 8

RUBILASH_MULTS["yellow"]["yellow"] = 2
RUBILASH_MULTS["yellow"]["orange"] = 4
RUBILASH_MULTS["yellow"]["green"] = 4
RUBILASH_MULTS["yellow"]["black"] = 8

RUBILASH_MULTS["blue"]["blue"] = 2
RUBILASH_MULTS["blue"]["purple"] = 4
RUBILASH_MULTS["blue"]["green"] = 4
RUBILASH_MULTS["blue"]["black"] = 8

RUBILASH_MULTS["white"]["white"] = 2

RUBILASH_TEXT_COLOR_RED = "#FF0000"
RUBILASH_TEXT_COLOR_YELLOW = "#FFFF00"
RUBILASH_TEXT_COLOR_BLUE = "#0000FF"
RUBILASH_TEXT_COLOR_ORANGE = "#FF8800"
RUBILASH_TEXT_COLOR_PURPLE = "#AA00DD"
RUBILASH_TEXT_COLOR_GREEN = "#00FF00"
RUBILASH_TEXT_COLOR_BLACK = "#000000"
RUBILASH_TEXT_COLOR_WHITE = "#FFFFFF"

RUBILASH_PHANTOM_BRUSH_CAST_POINT = 0.8
RUBILASH_PHANTOM_BRUSH_DAMAGE = {500, 1600, 2700, 3800, 4900, 6000, 7100}
RUBILASH_PHANTOM_BRUSH_DAMAGE_WHITE = {1000, 3200, 5400, 7600, 9800, 12000, 14200}

RUBILASH_INK_BLOT_DAMAGE = {200, 800, 1400, 2000, 2600, 3200, 3800}
RUBILASH_INK_BLOT_DAMAGE_WHITE = {400, 1600, 2800, 4000, 5200, 6400, 7600}

RUBILASH_RUNE_Q1_CAST_RANGE = 10
RUBILASH_RUNE_Q2_ARMOR_AND_MAGIC_ARMOR_LOSS = -70
RUBILASH_RUNE_Q3_FEAR_DURATION = 0.12
RUBILASH_RUNE_Q3_FEAR_DURATION_BASE = 0.6
RUBILASH_RUNE_Q4_DEMON_AND_GHOST_AMP = 8

RUBILASH_RUNE_W1_EXTRA_PAINT_DURATION = 0.1
RUBILASH_RUNE_W2_ARMOR_PIERCE_AND_MAGIC_ARMOR_LOSS = -70
RUBILASH_RUNE_W3_ATTACK_SPEED = 15
RUBILASH_RUNE_W3_W_AMP = 5
RUBILASH_RUNE_W4_SLOW = -9

RUBILASH_RUNE_E1_MANA_RESTORE = 100
RUBILASH_RUNE_E1_ATTACK_PER_MANA = 0.01
RUBILASH_RUNE_E2_SPELL_PIERCE_AND_MAGIC_ARMOR_LOSS = -70
RUBILASH_RUNE_E3_PAINT_HEAL_PCT = 1
RUBILASH_RUNE_E4_HEALTH_PER_ATTR = 0.8

RUBILASH_RUNE_R1_SPELL_PIERCE_PER_AGI = 0.1
RUBILASH_RUNE_R2_INVIS_DURATION_BASE = 0.3
RUBILASH_RUNE_R2_INVIS_DURATION_SCALE = 0.2
RUBILASH_RUNE_R2_BAD_AND_ITEM_WHILE_INVIS = 2
RUBILASH_RUNE_R3_INTERVAL_BASE = 2
RUBILASH_RUNE_R3_INTERVAL_REDUCTION = -0.03
RUBILASH_RUNE_R3_MIN_INTERVAL = 0.21
RUBILASH_RUNE_R3_RANGE_BASE = 600
RUBILASH_RUNE_R3_RANGE_SCALE = 12
RUBILASH_RUNE_R4_PORTRAIT_DELAY_REDUCTION = -0.02
RUBILASH_RUNE_R4_PORTRAIT_MS_BONUS = 10




RUBILASH_GLYPH_1_1_PROJECTILE_SPEED_PCT = 120
RUBILASH_GLYPH_2_1_Q_BAD = 100
RUBILASH_GLYPH_3_1_RANGE = 300
RUBILASH_GLYPH_3_1_INTERVAL = 2
RUBILASH_GLYPH_4_1_MAGIC_ARMOR = 5000
RUBILASH_GLYPH_6_1_DAMAGE_INCREASE_PCT = 400
RUBILASH_GLYPH_7_1_DAMAGE_REDUCE_PCT = -50
RUBILASH_GLYPH_5_A_ATTACK_POWER_BONUS = 300

RUBILASH_IMMORTAL_WEAPON_1_Q_BAD = 100
RUBILASH_IMMORTAL_WEAPON_2_MAX_HEALTH_INCREASE = 250
RUBILASH_IMMORTAL_WEAPON_2_HEAL_REDUCTION = 60
RUBILASH_IMMORTAL_WEAPON_3_AGI_AND_INT_MULT_TO_PAINT = 1
RUBILASH_IMMORTAL_WEAPON_3_ATK_DMG_PCT_TO_PAINT = 5