ASTRAL_RANGER_Q1_RANGE = 20
ASTRAL_RANGER_Q2_DMG_PER_ATT = 0.01
ASTRAL_RANGER_Q2_PROC_CHANCE = 20
ASTRAL_RANGER_Q2_STEADFAST_THRESHOLD = 5
ASTRAL_RANGER_Q2_ARMOR_LOSS = -50
ASTRAL_RANGER_Q3_ATTACK_PCT_IN_SHROUD = 4
ASTRAL_RANGER_Q4_ATTACK_DAMAGE_PER_ATTRIBUTE = 0.1

ASTRAL_RANGER_W_DELAY = 0.2
ASTRAL_RANGER_W_PARTICLE = "particles/frostivus_herofx/drow_linear_arrow.vpcf"
ASTRAL_RANGER_W_ARROWS_COUNT = 11
ASTRAL_RANGER_W1_ATTRIBUTES_PER_STACK = 0.03
ASTRAL_RANGER_W1_MAX_STACKS_COUNT = 100
ASTRAL_RANGER_W1_DURATION = 6
ASTRAL_RANGER_W2_MULTIPLY_CHANCE = 10
ASTRAL_RANGER_W3_PARTICLE = "particles/frostivus_gameplay/astral_rune_c_b_linear_frost_arrow.vpcf"
ASTRAL_RANGER_W3_PROC_CHANCE = 20
ASTRAL_RANGER_W3_MULTIPLY_PERCENT = 0.1
ASTRAL_RANGER_W4_DURATION = 4
ASTRAL_RANGER_W4_MAX_STACKS_COUNT = 20
ASTRAL_RANGER_W4_MAGIC_ARMOR_LOSS = -8


ASTRAL_RANGER_E_PARTICLE1 = "particles/units/heroes/hero_wisp/wisp_relocate_marker_endpoint.vpcf"
ASTRAL_RANGER_E_PARTICLE2 = "particles/units/heroes/hero_dark_seer/dark_seer_surge_start.vpcf"
ASTRAL_RANGER_E_DELAY = 1
ASTRAL_RANGER_E1_START_DURATION = 1
ASTRAL_RANGER_E1_ADD_DURATION = 0.07
ASTRAL_RANGER_E1_MAX_STACKS_COUNT = 1
ASTRAL_RANGER_E1_PARTICLE = "particles/econ/items/mirana/mirana_crescent_arrow/ruins_boss_linear_destruction.vpcf"
ASTRAL_RANGER_E1_RADIUS = 350
ASTRAL_RANGER_E1_SPEED_FROM_RANGE = 7 / 10
ASTRAL_RANGER_E1_TRAVELS_COUNT = 1
ASTRAL_RANGER_E1_MAGIC_ARMOR_REDUCE = -20
ASTRAL_RANGER_E2_PARTICLE = "particles/roshpit/astral_ranger/e2_flash.vpcf"
ASTRAL_RANGER_E2_FIND_RADUIS = 700
ASTRAL_RANGER_E2_DURATION = 6
ASTRAL_RANGER_E2_DAMAGE_BONUS = 30
ASTRAL_RANGER_E2_ATTACK_SPEED = 12
ASTRAL_RANGER_E3_START_DURATION = 1
ASTRAL_RANGER_E3_ADD_DURATION = 0.1
ASTRAL_RANGER_E3_DAMAGE_REDUCTION = 35
ASTRAL_RANGER_E3_MAGIC_ARMOR = 80
ASTRAL_RANGER_E4_COSMIC_AMP = 5
ASTRAL_RANGER_E4_ALL_ATTRIBUTES = 12

ASTRAL_RANGER_R1_DAMAGE = 20
ASTRAL_RANGER_R2_DAMAGE_PCT = 8
ASTRAL_RANGER_R2_BASE_RADIUS = 50
ASTRAL_RANGER_ASTRAL_R2_RADIUS = 2
ASTRAL_RANGER_R2_STUN_DURATION = 0.03
ASTRAL_RANGER_R3_ATTACK_DAMAGE_PERCENT = 0.01
ASTRAL_RANGER_R3_FLAT_DAMAGE = 35
ASTRAL_RANGER_R3_DURATION = 20
ASTRAL_RANGER_R3_RADIUS = 1800
ASTRAL_RANGER_R4_PROC_CHANCE_INCREASE = 0.01

ASTRAL_RANGER_ARCANA1_Q1_ATTACK_RANGE_INCREASE = 15
ASTRAL_RANGER_ARCANA1_Q2_DMG_PER_ATT = 0.02
ASTRAL_RANGER_ARCANA1_Q2_ARMOR_LOSS = -80
ASTRAL_RANGER_ARCANA1_Q2_PROC_CHANCE = 20
ASTRAL_RANGER_ARCANA1_Q3_DAMAGE_BONUS = 5
ASTRAL_RANGER_ARCANA1_Q4_DAMAGE_PER_ATTRIBUTE = 0.15

ASTRAL_RANGER_ARCANA2_W_1_ATTRIBUTES = 0.03
ASTRAL_RANGER_ARCANA2_W_3_DAMAGE_PCT_ATK_POWER = 0.001
ASTRAL_RANGER_ARCANA2_R4_SLOW = 0.15
ASTRAL_RANGER_ARCANA2_W_4_ARMOR_PIERCE = 8

ASTRAL_RANGER_ARCANA3_ARMOR_AND_SPELL_PIERCE_REDUCE = -60
ASTRAL_RANGER_ARCANA3_Q2_ATK_DAMAGE_ADDED_TO_ARROW = 2
ASTRAL_RANGER_ARCANA3_Q2_ATK_POWER_PCT = 3

ASTRAL_RANGER_IMMORTAL_WEAPON_1_HEAL_PCT = 1
ASTRAL_RANGER_IMMORTAL_WEAPON_2_Q2_PROC_CHANCE = 40
ASTRAL_RANGER_IMMORTAL_WEAPON_2_ARCANA1_Q2_PROC_CHANCE = 40
ASTRAL_RANGER_IMMORTAL_WEAPON_3_VISION = 1000
ASTRAL_RANGER_IMMORTAL_WEAPON_3_ATTACK_RANGE = 400

ASTRAL_RANGER_GLYPH_1_1_DURATION = 12
ASTRAL_RANGER_GLYPH_2_1_PHOENIX_DAMAGE_AMP = 3
ASTRAL_RANGER_GLYPH_2_1_PHOENIX_SLOW = 100
ASTRAL_RANGER_GLYPH_3_1_PROC_CHANCE = 40
ASTRAL_RANGER_GLYPH_3_1_ARROWS_COUNT = 9
ASTRAL_RANGER_GLYPH_3_1_DAMAGE_MULTIPLIER = 2
ASTRAL_RANGER_GLYPH_4_1_DELAY = 0.5
ASTRAL_RANGER_GLYPH_4_1_CD_REDUCTION = 0.5
ASTRAL_RANGER_GLYPH_4_1_DURATION_REDUCTION_PCT = 25
ASTRAL_RANGER_GLYPH_5_1_CD_REDUCTION = 5
ASTRAL_RANGER_GLYPH_6_1_TARGETS = 10
ASTRAL_RANGER_GLYPH_6_1_DAMAGE_PERCENT = 0.5
ASTRAL_RANGER_GLYPH_6_1_ENEMIES_SEARCH_RADIUS = 550
ASTRAL_RANGER_GLYPH_7_1_R_DAMAGE_MULT = 10
ASTRAL_RANGER_GLYPH_7_1_EVASION_DURATION = 2
ASTRAL_RANGER_GLYPH_5_A_BASE_DAMAGE = 1500
	

--change E2 to R4 icon
