RED_GENERAL_Q1_ATTACK_DAMAGE_PROCENT = 1
RED_GENERAL_Q2_DURATION = 10
RED_GENERAL_Q2_MAX_STACKS_COUNT = 50
RED_GENERAL_Q2_ATTACK_DAMAGE = 5
RED_GENERAL_Q3_AMPLIFY_PERCENT = 2
RED_GENERAL_Q4_DURATION = 5
RED_GENERAL_Q4_MAX_STACKS_COUNT = 10
RED_GENERAL_Q4_RESIST_REDUCE_PROCENT = 20

RED_GENERAL_W1_DAMAGE_PERCENT = 1
RED_GENERAL_W1_DURATION = 3
RED_GENERAL_W2_MAGIC_ARMOR_REDUCTION = 0.5
RED_GENERAL_W2_DURATION = 30
RED_GENERAL_W2_MAX_STACKS_COUNT = 3
RED_GENERAL_W3_HEAL_FLAT = 15
RED_GENERAL_W3_HEAL_PCT = 0.02
RED_GENERAL_W4_AMPLIFY_PERCENT = 0.03

RED_GENERAL_E_RADIUS = 300

RED_GENERAL_E1_ATTRIBUTES_GAIN = 1
RED_GENERAL_E2_BONUS_DAMAGE_PERCENT = 1
RED_GENERAL_E3_DAMAGE_PERCENT = 1
RED_GENERAL_E4_PROC_CHANCE = 150
RED_GENERAL_E4_DURATION = 7

RED_GENERAL_R1_DAMAGE = 10
RED_GENERAL_R1_BUFF_DURATION = 10
RED_GENERAL_R2_AMPLIFY_PERCENT = 2
RED_GENERAL_R3_DURATION = 12
RED_GENERAL_R3_BONUS_HEALTH = 200
RED_GENERAL_R3_BONUS_ARMOR = 40
RED_GENERAL_R4_POST_AMP_PERCENT = 1

RED_GENERAL_ARCANA1_R_RADIUS = 1000
RED_GENERAL_ARCANA1_R1_AMPLIFY_PERCENT = 1
RED_GENERAL_ARCANA1_R2_DURATION = 12
RED_GENERAL_ARCANA1_R2_MAX_STACKS_COUNT = 5
RED_GENERAL_ARCANA1_R2_BONUS_DAMAGE = 50
RED_GENERAL_ARCANA1_R3_RESIST_REDUCE_PERCENT = 5
RED_GENERAL_ARCANA1_R3_DURATION = 100
RED_GENERAL_ARCANA1_R4_ADD_TREMOR_CHANCE = 10
RED_GENERAL_ARCANA1_R4_INCREASE_RADIUS = 30

RED_GENERAL_ARCANA2_W1_ARMOR_AND_SPELL_PIERCE = 5
RED_GENERAL_ARCANA2_W2_ARMOR = 20
RED_GENERAL_ARCANA2_W2_STRENGTH = 20
RED_GENERAL_ARCANA2_W3_DMG_PCT_ATK_POWER = 10
RED_GENERAL_ARCANA2_W3_RADIUS_BASE = 150
RED_GENERAL_ARCANA2_W3_RADIUS_GROWTH = 30

RED_GENERAL_GLYPH_1_1_DMG_REDUCTION_PCT = 30
RED_GENERAL_GLYPH_3_1_E_INTERVAL_REDUCTION = 0.5
RED_GENERAL_GLYPH_4_1_DAMAGE_PROCENT = 60
RED_GENERAL_GLYPH_5_1_Q_STUN = 0.03
RED_GENERAL_GLYPH_5_1_Q_DAMAGE_AMP = 3
RED_GENERAL_GLYPH_6_1_DUNKS_COUNT = 3
RED_GENERAL_GLYPH_7_1_Q_CD = 1.5

RED_GENERAL_GLYPH_5_A_AMPLIFY_PERCENT = 50

RED_GENERAL_GLYPH_1_2_STUN_DURATION = 0.08
RED_GENERAL_GLYPH_2_2_ARMOR_DECREASE = 250
RED_GENERAL_GLYPH_3_2_STACKS_GAIN = 4
RED_GENERAL_GLYPH_4_2_DAMAGE_REDUCTION_PERCENT = 50 -- don't affect game_state.lua
RED_GENERAL_GLYPH_5_2_AMPLIFY_DURATION = 9
RED_GENERAL_GLYPH_5_2_AMPLIFY_PERCENT = 200
RED_GENERAL_GLYPH_6_2_DAMAGE_REDUCTION_PERCENT = 90 -- don't affect game_state.lua
RED_GENERAL_GLYPH_6_2_SHIELD_CHANCE_PERCENT = 100
RED_GENERAL_GLYPH_7_2_MAX_STACKS_COUNT = 75
RED_GENERAL_GLYPH_7_2_AMP_STACKS_PER_ATTACK = 3

RED_GENERAL_IMMORTAL_WEAPON_DMG_REDUCTION = 0.5
RED_GENERAL_IMMORTAL_WEAPON_2_AMPLIFY_PERCENT = 200
RED_GENERAL_IMMORTAL_WEAPON_2_ADD_MOVESPEED = 300
RED_GENERAL_IMMORTAL_WEAPON_3_BONUS_SHIELDS_PERCENT = 100


