SOLUNIA_Q1_DMG_PER_ATT_PCT = 8
SOLUNIA_Q1_PUSH_FORCE = 1
SOLUNIA_Q2_BASE_ATTACK = 2
SOLUNIA_Q2_BONUS_ATTACK_PCT = 0.02
SOLUNIA_Q3_CURRENT_HP_BONUS_PCT = 0.4
SOLUNIA_Q3_MISSING_HP_BONUS_PCT = 0.4
SOLUNIA_Q4_COSMIC_AMP_PCT = 0.1

SOLUNIA_W1_CRIT_CHANCE_BASE = 15
SOLUNIA_W1_CRIT_CHANCE = 0.1
SOLUNIA_W1_CRIT_DAMAGE_PCT = 12
SOLUNIA_W2_DMG_AMP = 15
SOLUNIA_W3_ATTACK_TO_DMG_PCT = 0.02
SOLUNIA_W4_BONUS_DAMAGE_PCT = 12
SOLUNIA_W4_DURATION_BASE = 3.0
SOLUNIA_W4_DURATION = 0.9

SOLUNIA_E1_EXPLOSION_PCT_BASE = 100
SOLUNIA_E1_EXPLOSION_PCT = 20
SOLUNIA_E1_STUN_DUR = 0.08
SOLUNIA_E2_EXPLOSION_PCT = 8
SOLUNIA_E2_STUN_DUR = 0.05
SOLUNIA_E3_DUR_BASE = 1
SOLUNIA_E3_DUR = 0.3
SOLUNIA_E3_ARMOR_LOSS = -50
SOLUNIA_E4_HP = 800

SOLUNIA_R1_HP = 300
SOLUNIA_R1_MANA = 200
SOLUNIA_R2_DMG_PER_DMG = 0.008
SOLUNIA_R2_DUAL_BURN_AMP = 0.04
SOLUNIA_R2_DUR_BASE = 8
SOLUNIA_R3_WAVE_DMG_PCT = 5
SOLUNIA_R3_RANGE_BASE = 600
SOLUNIA_R3_RANGE = 6
SOLUNIA_R4_CD_RED = 0.2
SOLUNIA_R4_ADD_DMG_PER_ATTR = 0.5

SOLUNIA_ARCANA_Q1_HP_REGEN = 60
SOLUNIA_ARCANA_Q1_BONUS_ATTACK_PCT = 3
SOLUNIA_ARCANA_Q2_BASE_ATTACK_PER_HP = 0.01
SOLUNIA_ARCANA_Q2_BASE_ATTACK_PER_HP_LUNAR = 0.02
SOLUNIA_ARCANA_Q3_ARMOR_LOSS = -8
SOLUNIA_ARCANA_Q3_ATTACK_TO_DMG_PCT = 2
SOLUNIA_ARCANA_Q4_COSMIC_AMP_PCT = 0.15

SOLUNIA_ARCANA_R1_MIN = 10
SOLUNIA_ARCANA_R1_MAX = 400
SOLUNIA_ARCANA_R2_PIERCE = 35
SOLUNIA_ARCANA_R3_DURATION = 0.25
SOLUNIA_ARCANA2_R3_DAMAGE_REDUCTION_PCT = 0.9
SOLUNIA_ARCANA_R4_ELEM_AMP_PCT = 0.04
SOLUNIA_ARCANA_R4_ATTRIBUTES = 40

SOLUNIA_ARCANA_W1_ATK_DMG_ADDED_TO_VORPAL_PCT = 2
SOLUNIA_ARCANA_W2_MANA_RESTORE_PER_HIT = 4
SOLUNIA_ARCANA_W2_CURRENT_MANA_ADDED_TO_DAMAGE_PCT = 1
SOLUNIA_ARCANA_W3_CRIT_DMG = 10
SOLUNIA_ARCANA_W4_EXTRA_BOUNCE_CHANCE = 20

SOLUNIA_GLYPH_1_1_W_BLADES_ADDED = 2

SOLUNIA_GLYPH_2_1_W_HIT_Q_CD_REDUCTION = 2

SOLUNIA_GLYPH_3_1_Q_STUN_DURATION_ADDED = 1

SOLUNIA_GLYPH_4_1_E_FLOATING_DURATION_ADDED = 1.5

SOLUNIA_GLYPH_5_1_STACKS_BASE = 3

SOLUNIA_GLYPH_6_1_DURATION = 8

SOLUNIA_GLYPH_7_1_E_CASTS_ADDED = 2

SOLUNIA_GLYPH_5_A_CD = 18

SOLUNIA_IMMORTAL_WEAPON_2_CRIT_FREEZE_AOE = 200
SOLUNIA_IMMORTAL_WEAPON_2_CRIT_FREEZE_DURATION = 1.5
