SOLUNIA_STATE_SOLAR = 0
SOLUNIA_STATE_LUNAR = 1

SOLUNIA_Q1_BUFF_DURATION = 24
SOLUNIA_Q1_MAX_STACKS = 12
SOLUNIA_Q1_BASE_DMG_PER_STACK_SOLAR = 15
SOLUNIA_Q1_DMG_PCT_PER_STACK_LUNAR = 0.3
SOLUNIA_Q2_BASE_DMG_INCREASE_PER_MANA = 0.2
SOLUNIA_Q2_MANA_COST = 60
SOLUNIA_Q3_Q_BAD = 10
SOLUNIA_Q3_Q_SPEED_INCREASE_PCT = 3
SOLUNIA_Q4_ELEMENTAL_AMP = 12

SOLUNIA_W_MANA_COST = {45, 85, 125, 165, 205, 245, 285}

SOLUNIA_W1_CRIT_CHANCE = 15
SOLUNIA_W1_CRIT_DAMAGE = 15
SOLUNIA_W2_RADIUS = 260
SOLUNIA_W2_EXPLOSION_DAMAGE = 15
SOLUNIA_W3_CAST_POINT_REDUCTION_PCT = 1.5
SOLUNIA_W3_CAST_RANGE = 40
SOLUNIA_W4_PIERCE_PER_BOOMERANG = 150

SOLUNIA_E_FLOAT_TIME = 2
SOLUNIA_E_TRAVEL_SPEED = 80
SOLUNIA_E_HEIGHT_GAIN = 15
SOLUNIA_E_MAX_HEIGHT = 320

SOLUNIA_E1_HEALTH_REGEN = 60
SOLUNIA_E1_ARMORS = 120
SOLUNIA_E2_PAD_DURATION = 16
SOLUNIA_E2_PAD_RADIUS = 240
SOLUNIA_E2_MS_LOSS = -10
SOLUNIA_E2_ARMORS_LOSS = -150
SOLUNIA_E3_HEALTH_BONUS = 500
SOLUNIA_E4_CAST_RANGE = 40
SOLUNIA_E4_WARPSPEED_PCT = 3

SOLUNIA_R_HEIGHT_FOR_ATTACK_IMMUNE = 190
SOLUNIA_R1_CD_REDUCE = 0.1
SOLUNIA_R1_R_BAD = 2
SOLUNIA_R2_DUAL_BURN_MULT = 2
SOLUNIA_R2_DUAL_BURN_DURATION = 8
SOLUNIA_R2_DUAL_BURN_DMG_PCT_SUPERNOVA = 0.4
SOLUNIA_R3_ATTRIBUTE_BONUS = 40
SOLUNIA_R4_CD_REDUCE = 0.5
SOLUNIA_R4_COSMIC_AMP = 8

SOLUNIA_ARCANA_Q1_HP_REGEN = 60
SOLUNIA_ARCANA_Q1_BONUS_ATTACK_PCT = 3
SOLUNIA_ARCANA_Q2_BASE_ATTACK_PER_HP = 0.01
SOLUNIA_ARCANA_Q2_BASE_ATTACK_PER_HP_LUNAR = 0.02
SOLUNIA_ARCANA_Q3_DURATION = 60
SOLUNIA_ARCANA_Q3_ARMOR_LOSS = -8
SOLUNIA_ARCANA_Q3_ATTACK_TO_DMG_PCT = 2
SOLUNIA_ARCANA_Q4_COSMIC_AMP_PCT = 0.15

SOLUNIA_ARCANA_R1_MIN = 10
SOLUNIA_ARCANA_R1_MAX = 400
SOLUNIA_ARCANA_R2_PIERCE = 35
SOLUNIA_ARCANA_R3_DURATION = 0.25
SOLUNIA_ARCANA2_R3_DAMAGE_REDUCTION_PCT = 0.9
SOLUNIA_ARCANA_R4_ELEM_AMP_PCT = 0.04
SOLUNIA_ARCANA_R4_ATTRIBUTES = 40

SOLUNIA_ARCANA_W1_ATK_DMG_ADDED_TO_VORPAL_PCT = 1.5
SOLUNIA_ARCANA_W2_MANA_RESTORE_PER_HIT = 4
SOLUNIA_ARCANA_W2_CURRENT_MANA_ADDED_TO_DAMAGE_PCT = 2
SOLUNIA_ARCANA_W3_CRIT_DMG = 8
SOLUNIA_ARCANA_W3_CRIT_CHANCE = 25
SOLUNIA_ARCANA_W4_EXTRA_BOUNCE_CHANCE = 20

SOLUNIA_GLYPH_1_1_W_BLADES_ADDED = 2

SOLUNIA_GLYPH_2_1_W_HIT_Q_CD_REDUCTION = 2

SOLUNIA_GLYPH_3_1_Q_STUN_DURATION_ADDED = 1

SOLUNIA_GLYPH_4_1_E_FLOATING_DURATION_ADDED = 1.5

SOLUNIA_GLYPH_5_1_STACKS_BASE = 3

SOLUNIA_GLYPH_6_1_DURATION = 8

SOLUNIA_GLYPH_7_1_E_CASTS_ADDED = 2

SOLUNIA_GLYPH_5_A_CD = 18

SOLUNIA_IMMORTAL_WEAPON_2_CRIT_FREEZE_AOE = 200
SOLUNIA_IMMORTAL_WEAPON_2_CRIT_FREEZE_DURATION = 1.5
