EPOCH_Q1_DMG_MULTI_PCT = 5
EPOCH_Q1_ADDITIONAL_LINKS_CHANCE = 10
EPOCH_Q2_FLAT_DMG = 30
EPOCH_Q2_FLAT_DMG_NEGATIVE = -30
EPOCH_Q2_DAMAGE_SHARE = 1
EPOCH_Q3_TIMES_MANA_DRAINED = 0.01
EPOCH_Q3_BASE_MANA_DRAIN_PCT = 10
EPOCH_Q4_DMG_BONUS_PCT = 0.5
EPOCH_Q4_Q3_BONUS_MANA_DRAIN_PCT = 0.1
EPOCH_Q4_MANA_DRAIN_BASE_PCT = 0.5

EPOCH_W1_HP_RESTORE = 4
EPOCH_W1_DURATION = 2
EPOCH_W1_THINK_INTERVAL = 0.2
EPOCH_W2_MAGIC_ARMOR_REDUCTION = -5
EPOCH_W2_MAX_STACKS = 7
EPOCH_W2_DURATION = 6
EPOCH_W3_HEAL = 50
EPOCH_W3_INT = 2
EPOCH_W3_MAX_STACKS = 10
EPOCH_W4_DMG_MULTI_PCT = 1
EPOCH_W4_MANA_DRAIN_BASE_PCT = 0.05

EPOCH_E1_DURATION = 0.09
EPOCH_E2_DMG_BASE = 30
EPOCH_E2_DMG = 40
EPOCH_E2_ORBS = 1
EPOCH_E3_TARGETS_BASE = 1
EPOCH_E3_TARGETS = 1
EPOCH_E3_ATTACK_DAMAGE_PCT = 80
EPOCH_E4_DMG_MULTI_PCT = 2

EPOCH_R1_DMG_PCT = 0.05
EPOCH_R1_PER_MANA = 100
EPOCH_R1_EXTRA_DURATION = 0.5
EPOCH_R2_ATTACK_RANGE = 4
EPOCH_R2_ATTACK_SPEED = 5
EPOCH_R3_DMG_MULTI_PCT = 4
EPOCH_R4_TIME_AMP = 0.12

EPOCH_ARCANA_Q1_DMG_MULTI_PCT = 5
EPOCH_ARCANA_Q2_ARMOR_AND_SPELL_PIERCE = 20
EPOCH_ARCANA_Q3_DMG_MULTI_PCT = 0.02
EPOCH_ARCANA_Q3_BASE_MANA_DRAIN_PCT = 20
EPOCH_ARCANA_Q3_EXTRA_BASE_ATT_DMG_PCT = 0.15
EPOCH_ARCANA_Q4_PROCS_PCT = 50

EPOCH_GLYPH_1_1_Q1_DAMAGE_INCREASED_PCT = 50
EPOCH_GLYPH_1_1_DURATION = 7
EPOCH_GLYPH_2_1_E_SPEED_BONUS_PCT = 60
EPOCH_GLYPH_2_1_E_DISTANCE_BONUS_PCT = 60
EPOCH_GLYPH_2_1_E2_DURATION_AMP = 2
EPOCH_GLYPH_3_1_MANA_X_ABILITYLVL_TO_W_PCT = 200
EPOCH_GLYPH_4_1_ = 0
EPOCH_GLYPH_5_1_ = 0
EPOCH_GLYPH_6_1_ATTACK_DMG_REDUCTION_PCT = 80
EPOCH_GLYPH_6_1_Q2_MULTI = 10
EPOCH_GLYPH_6_1_DURATION = 7
EPOCH_GLYPH_7_1_ = 0
EPOCH_GLYPH_5_A_SECOND_LIFE_CD = 15

EPOCH_IMMORTAL_WEAPON_1_ORBS = 3
EPOCH_IMMORTAL_WEAPON_1_DAMAGE_AMP = 1.5
EPOCH_IMMORTAL_WEAPON_2_RESPAWN_DELAY = 3
EPOCH_IMMORTAL_WEAPON_2_R_CD_MULT = 1.5
EPOCH_IMMORTAL_WEAPON_3_STUN = 0.8

