SEPHYR_Q1_INT_BONUS = 125
SEPHYR_Q2_POSTMIT = 0.1
SEPHYR_Q3_STACKS = 1
SEPHYR_Q3_HOLY_AMP_PCT = 10
SEPHYR_Q4_HOLY_AMP_PCT = 100
SEPHYR_Q4_HOLY_TO_ATT_BONUS_PCT = 0.5

SEPHYR_W_BASE_RANGE = 800
SEPHYR_W_BASE_PARTICLE_SPEED = 2500
SEPHYR_W1_INT_TO_MANA_REGEN_PCT = 2.5
SEPHYR_W2_CRIT_BONUS_PCT = 20
SEPHYR_W3_ATTACK_TO_DAMAGE_PCT = 2
SEPHYR_W4_WIND_AMP_PCT = 0.12

SEPHYR_E1_BOUNCE_CHANCE = 10
SEPHYR_E1_DAMAGE = 1500
SEPHYR_E2_BONUS_ATTACK_DAMAGE = 800
SEPHYR_E2_ATTACK_TO_DAMAGE_PCT = 15
SEPHYR_E3_BASE_ATTACK_DAMAGE_PER_AGI = 0.2
SEPHYR_E3_BONUS_PUCK_DAMAGE_PER_AGI = 1.5
SEPHYR_E4_STRAFE_SPEED = 0.15
SEPHYR_E4_STRAFE_DISTANCE = 6

SEPHYR_R1_HP_REGEN_PER_LVL = 20
SEPHYR_R2_ATT_SPEED_SLOW = -8
SEPHYR_R2_MS_SPEED_SLOW = -10
SEPHYR_R3_MOVESPEED = 10
SEPHYR_R3_STRAFE_SPEED = 0.12
SEPHYR_R4_BONUS_INT = 500
SEPHYR_R4_BONUS_AGI = 500

SEPHYR_GLYPH_1_1_ADDITIONAL_E1_PUCK = 1
SEPHYR_GLYPH_2_1_EVASION_PCT = 80
SEPHYR_GLYPH_3_1_R_BONUS_RADIUS = 180
SEPHYR_GLYPH_4_1_W_BONUS_RANGE = 400 
SEPHYR_GLYPH_4_1_W_BONUS_PARTICLE_SPEED = 1000
SEPHYR_GLYPH_5_1_Q_FREEZE_DUR = 1.4
SEPHYR_GLYPH_6_1_DAMAGE_NEGATION_CHANCE = 35
SEPHYR_GLYPH_7_1_Z_DISTANCE_FOR_IMMUNITY = 380
SEPHYR_GLYPH_7_1_DURATION = 1
SEPHYR_GLYPH_5_A_R_DMG_REDUCTION_PCT = 99.5

SEPHYR_IMMORTAL_WEAPON_1_CRIT_CHANCE_INCREASE = 15
SEPHYR_IMMORTAL_WEAPON_1_W_WIDTH_INCREASE_PCT = 100

SEPHYR_IMMORTAL_WEAPON_2_ADDITIONAL_E1_PUCKS = 3

SEPHYR_IMMORTAL_WEAPON_3_T4_RUNES = 7

SEPHYR_ARCANA_W1_MANA_REGEN_FLAT = 35
SEPHYR_ARCANA_W1_DAMAGE_PER_MANAREGEN = 0.3
SEPHYR_ARCANA_W2_ATTACK_TO_DAMAGE_PCT = 4
SEPHYR_ARCANA_W3_SHIELD_CHANCE = 4
SEPHYR_ARCANA_W4_WIND_AMP_PCT = 0.15

SEPHYR_ARCANA_GALE_RANGE = 800
SEPHYR_ARCANA_GALE_SPEED = 2500
SEPHYR_ARCANA_GALE_CRIT_CHANCE = 15