HYDROXIS_Q1_DMG_PCT = 8
HYDROXIS_Q2_ARMOR = 12
HYDROXIS_Q2_HEAL = 200
HYDROXIS_Q3_MAGIC_RESIST = 1.5
HYDROXIS_Q4_MULTI_CAST_PCT = 10
HYDROXIS_Q4_ADD_DMG_PER_ATTR = 30

HYDROXIS_W1_SPLASH_PCT = 5
HYDROXIS_W2_BONUS_ATTACK_DMG_PCT = 4
HYDROXIS_W3_ATTACK_TO_DMG_PCT = 8
HYDROXIS_W4_DMG_PER_MANA_PCT = 0.2
HYDROXIS_W4_MANA_DRAIN_PCT = 3

HYDROXIS_E1_PCT_OF_W = 10
HYDROXIS_E2_ATTACK_TO_DMG_PCT = 10
HYDROXIS_E3_ATTACK_SPEED = 10
HYDROXIS_E4_BONUS_AGI_INT = 350
HYDROXIS_E4_WATER_AMP = 0.1

HYDROXIS_R1_ARMOR_RED = 100
HYDROXIS_R1_BAD_PCT_PER_ARMOR = 0.00002 --0.02% per 10 armor
HYDROXIS_R1_RUNE_MULT = 0.6
HYDROXIS_R2_DMG = 85000
HYDROXIS_R3_RADIUS_BASE = 300
HYDROXIS_R3_ATTACK_TO_DMG_PCT = 35
HYDROXIS_R4_DMG_AMP_PCT = 20
HYDROXIS_R4_DMG_RED_PCT = 1.5

HYDROXIS_GLYPH_1_1_R_REPEAT_NUMBER_OF_REPEATS = 1
HYDROXIS_GLYPH_1_1_R_REPEAT_DELAY = 2
HYDROXIS_GLYPH_2_1_E1_INTERVAL_RED_PCT = 50 --not implemented, tooltips only
HYDROXIS_GLYPH_3_1_Q2_TICKRATE_MULT = 2
HYDROXIS_GLYPH_4_1_E2_DMG_AMP = 3
HYDROXIS_GLYPH_5_1_CHANCE = 15
HYDROXIS_GLYPH_5_1_W1_MAGIC_AMP = 4
HYDROXIS_GLYPH_6_1_R4_RADIUS_INCREASE = 200 -- particle involved, not implemented, tooltips only
HYDROXIS_GLYPH_7_1_R3_DURATION_INCREASE = 5


HYDROXIS_IMMORTAL_WEAPON_1_R3_DMG_AMP_PCT = 100
HYDROXIS_IMMORTAL_WEAPON_1_R4_RADIUS_AMP_PCT = 50

HYDROXIS_IMMORTAL_WEAPON_2_STUN_DURATION = 1.2

HYDROXIS_IMMORTAL_WEAPON_3_Q_DELAY_REDUCTION_PCT = 50

HYDROXIS_ARCANA_W1_SPLASH_PCT = 7.5
HYDROXIS_ARCANA_W2_ATTACK_TO_DMG = 10
HYDROXIS_ARCANA_W3_POST_MITI_PCT = 6
HYDROXIS_ARCANA_W4_MIST_DURATION_BASE = 0.5
HYDROXIS_ARCANA_W4_MIST_DURATION = 0.15
HYDROXIS_ARCANA_W4_BASE_ATTACK = 2500

HYDROXIS_ARCANA_R1_RANGE = 15
HYDROXIS_ARCANA_R1_BAD_PCT = 7.5
HYDROXIS_ARCANA_R2_DURATION_INC = 0.25
HYDROXIS_ARCANA_R3_ROOT_DUR_BASE = 1
HYDROXIS_ARCANA_R3_ROOT_DUR = 0.15
HYDROXIS_ARCANA_R3_WATER_AMP_PCT = 30
HYDROXIS_ARCANA_R4_INT_BONUS = 500
HYDROXIS_ARCANA_R4_POST_MITI_PCT = 10