local prefix = 'items/lua/trinket/'
-- require(prefix..'stargazers_sphere')
require(prefix..'neverlord_soul_ring')
require(prefix..'signus_charm')
require(prefix..'moon_shard')
require(prefix..'horn_of_the_triumphant')
require(prefix..'mortuary_charm')
require(prefix..'baphomets_cursed_necklace')
require(prefix..'monarch_ring')

require(prefix..'volcano_orb')
require(prefix..'firelock_pendant')
require(prefix..'garnet_warfare_ring')
require(prefix..'sparkling_token_of_oceanis')
require(prefix..'arbor_dragonfly')
require(prefix..'conquest_stone_falcon')
require(prefix..'lifesource_vessel')
