-----------------
--- Q ABILITY ---
-----------------



-----------------
--- W ABILITY ---
-----------------
--- LIGHTNING LIGHTNING W ---
JEX_LIGHTNING_LIGHTNING_W_MANA_COST = {20, 45, 70, 95, 120, 145, 170}
JEX_LIGHTNING_LIGHTNING_W_DAMAGE_TYPE = DAMAGE_TYPE_MAGICAL
JEX_LIGHTNING_LIGHTNING_W_DAMAGE_PCT = {6, 8, 10, 12, 14, 16, 18}
JEX_LIGHTNING_LIGHTNING_W_BONUS_ATTACKSPEED = {180, 195, 210, 225, 240, 255, 270}
JEX_LIGHTNING_LIGHTNING_W_BONUS_DAMAGE_PCT_PER_TECH = 8
JEX_LIGHTNING_LIGHTNING_W_CHAIN_PER_TECH = 1
JEX_LIGHTNING_LIGHTNING_W_BASE_DMG_PER_AGI_PER_W4 = 0.1


-----------------
--- E ABILITY ---
-----------------



-----------------
--- R ABILITY ---
-----------------




------------------------
--- Q ARCANA ABILITY ---
------------------------




--------------
--- GLYPHS ---
--------------
JEX_GLYPH_1_HARVEST_RADIUS = 600
JEX_GLYPH_3_SLOW = -360
JEX_GLYPH_3_DURATION = 1.2
JEX_GLYPH_4_ATTACKSPEED = 140
JEX_GLYPH_5_DAMAGE_DEALT_PERCENT = -30
JEX_GLYPH_5_A_TECH = 1

JEX_GLYPH_7_DAMAGE_PCT = 100
JEX_GLYPH_7_RADIUS = 800


------------------------
--- IMMORTAL WEAPONS ---
------------------------



JEX_Q_COSMIC_COSMIC_MAGIC_ARMOR_LOSS = -150
JEX_OAK_INFUSION_Q4_STR = 20
JEX_NATURE_COSMIC_E_Q4_ARMOR_AND_MAGIC_ARMOR = 45
JEX_COSMIC_SURGE_E4_COSMIC_AMP = 0.04

JEX_RUNE_ROW_1_VALUE = 0.06
JEX_RUNE_ROW_2_VALUE = 0.015
JEX_RUNE_ROW_3_VALUE = 0.08

JEX_RUNE_BASE_ABILITY_R1 = 2.1
JEX_RUNE_BASE_ABILITY_R2 = 2.1
JEX_RUNE_BASE_ABILITY_R3 = 4.2

JEX_RUNE_R4_SPELL_PIERCE = 150

