--ELEMENTS--
RPC_ELEMENT_COUNT = 18

RPC_ELEMENT_NONE = -1
RPC_ELEMENT_NORMAL = 1
RPC_ELEMENT_FIRE = 2
RPC_ELEMENT_EARTH = 3
RPC_ELEMENT_LIGHTNING = 4
RPC_ELEMENT_POISON = 5
RPC_ELEMENT_TIME = 6
RPC_ELEMENT_HOLY = 7
RPC_ELEMENT_COSMOS = 8
RPC_ELEMENT_ICE = 9
RPC_ELEMENT_ARCANE = 10
RPC_ELEMENT_SHADOW = 11
RPC_ELEMENT_WIND = 12
RPC_ELEMENT_GHOST = 13
RPC_ELEMENT_WATER = 14
RPC_ELEMENT_DEMON = 15
RPC_ELEMENT_NATURE = 16
RPC_ELEMENT_UNDEAD = 17
RPC_ELEMENT_DRAGON = 18

RPC_ELEMENT_NORMAL_COLOR = "#DDDDDD"
RPC_ELEMENT_FIRE_COLOR = "#EF4126"
RPC_ELEMENT_EARTH_COLOR = "#AF843D"
RPC_ELEMENT_LIGHTNING_COLOR = "#5CCDF9"
RPC_ELEMENT_POISON_COLOR = "#37DD3D"
RPC_ELEMENT_TIME_COLOR = "#B5FFB7"
RPC_ELEMENT_HOLY_COLOR = "#F6FFB5"
RPC_ELEMENT_COSMOS_COLOR = "#C25DFC"
RPC_ELEMENT_ICE_COLOR = "#87D9FF"
RPC_ELEMENT_ARCANE_COLOR = "#E1A2E8"
RPC_ELEMENT_SHADOW_COLOR = "#7F4F84"
RPC_ELEMENT_WIND_COLOR = "#7AE2A7"
RPC_ELEMENT_GHOST_COLOR = "#9ACCD1"
RPC_ELEMENT_WATER_COLOR = "#3894FF"
RPC_ELEMENT_DEMON_COLOR = "#5B648C"
RPC_ELEMENT_NATURE_COLOR = "#69BC71"
RPC_ELEMENT_UNDEAD_COLOR = "#5C776E"
RPC_ELEMENT_DRAGON_COLOR = "#3289C7"

-- ELEMENT_TOOLTIP_NORMAL = "<font color='#DDDDDD'>Normal</font>"
-- ELEMENT_TOOLTIP_FIRE = "<font color='#EF4126'>Fire</font>"
-- ELEMENT_TOOLTIP_EARTH = "<font color='#AF843D'>Earth</font>"
-- ELEMENT_TOOLTIP_LIGHTNING = "<font color='#5CCDF9'>Lightning</font>"
-- ELEMENT_TOOLTIP_POISON = "<font color='#37DD3D'>Poison</font>"
-- ELEMENT_TOOLTIP_TIME = "<font color='#B5FFB7'>Temporal</font>"
-- ELEMENT_TOOLTIP_HOLY = "<font color='#F6FFB5'>Holy</font>"
-- ELEMENT_TOOLTIP_COSMOS = "<font color='#C25DFC'>Cosmic</font>"
-- ELEMENT_TOOLTIP_ICE = "<font color='#87D9FF'>Ice</font>"
-- ELEMENT_TOOLTIP_ARCANE = "<font color='#E1A2E8'>Arcane</font>"
-- ELEMENT_TOOLTIP_SHADOW = "<font color='#7F4F84'>Shadow</font>"
-- ELEMENT_TOOLTIP_WIND = "<font color='#7AE2A7'>Wind</font>"
-- ELEMENT_TOOLTIP_GHOST = "<font color='#9ACCD1'>Ghost</font>"
-- ELEMENT_TOOLTIP_WATER = "<font color='#3894FF'>Water</font>"
-- ELEMENT_TOOLTIP_DEMON = "<font color='#5B648C'>Demon</font>"
-- ELEMENT_TOOLTIP_NATURE = "<font color='#69BC71'>Nature</font>"
-- ELEMENT_TOOLTIP_UNDEAD = "<font color='#5C776E'>Undead</font>"
-- ELEMENT_TOOLTIP_DRAGON = "<font color='#3289C7'>Dragon</font>"
-- DOESNT WORK :'(

--SKILL SLOTS--
DOTA_Q_SLOT = 0
DOTA_W_SLOT = 1
DOTA_E_SLOT = 2
DOTA_D_SLOT = 3
DOTA_F_SLOT = 4
DOTA_R_SLOT = 5

--BASE--
BASE_NONE = -1
BASE_ITEM = 0
BASE_ABILITY_Q = 1
BASE_ABILITY_W = 2
BASE_ABILITY_E = 3
BASE_ABILITY_R = 4
BASE_AUTO_ATTACK = 5

--ENEMY TYPE--
ENEMY_TYPE_WEAK_CREEP = 0
ENEMY_TYPE_NORMAL_CREEP = 1
ENEMY_TYPE_ELITE_CREEP = 2
ENEMY_TYPE_MINI_BOSS = 3
ENEMY_TYPE_BOSS = 4
ENEMY_TYPE_MAJOR_BOSS = 5

--DIFFICULTY--
DIFFICULTY_NORMAL = 1
DIFFICULTY_ELITE = 2
DIFFICULTY_LEGEND = 3

NPC_LUA_UNIT = 'lua_unit'

--Modifier special types--

-- DAMAGE --
MODIFIER_SPECIAL_TYPE_ABILITIES = 1
MODIFIER_SPECIAL_TYPE_ITEMS = 2
MODIFIER_SPECIAL_TYPE_ELEMENTS = 3 -- added to current calculation
MODIFIER_SPECIAL_TYPE_STEADFAST = 4
MODIFIER_SPECIAL_TYPE_POSTMITIGATION = 5 -- added to current calculation
MODIFIER_SPECIAL_TYPE_EXTRA_POSTMITIGATION = 6 -- added to current calculation
MODIFIER_SPECIAL_TYPE_PREMITIGATION = 7
MODIFIER_SPECIAL_TYPE_LETHAL_CHECK = 8
MODIFIER_SPECIAL_TYPE_LETHAL = 9 -- added to current calculation
MODIFIER_SPECIAL_TYPE_AUGMENTED = 10
MODIFIER_SPECIAL_TYPE_DOT = 11

-- Other --
MODIFIER_SPECIAL_TYPE_ORDER_FILTER = 12
MODIFIER_SPECIAL_TYPE_CAST_Q_ABILITY = 13
MODIFIER_SPECIAL_TYPE_CAST_W_ABILITY = 14
MODIFIER_SPECIAL_TYPE_CAST_E_ABILITY = 15
MODIFIER_SPECIAL_TYPE_CAST_R_ABILITY = 16

MODIFIER_SPECIAL_TYPE_ON_HIT_Q_ABILITY = 17
MODIFIER_SPECIAL_TYPE_ON_HIT_W_ABILITY = 18
MODIFIER_SPECIAL_TYPE_ON_HIT_E_ABILITY = 19
MODIFIER_SPECIAL_TYPE_ON_HIT_R_ABILITY = 20

-------------------
-- ROSHPIT STATS --
-------------------
--Armor--
MODIFIER_ROSHPIT_BASE_ARMOR_BONUS = 21
MODIFIER_ROSHPIT_ARMOR_BONUS = 22
--Armor Pierce--
MODIFIER_ROSHPIT_ARMOR_PIERCE_BONUS = 23
--Magic Armor--
MODIFIER_ROSHPIT_BASE_MAGIC_ARMOR_BONUS = 24
MODIFIER_ROSHPIT_MAGIC_ARMOR_BONUS = 25
--Spell Pierce--
MODIFIER_ROSHPIT_SPELL_PIERCE_BONUS = 26
--Attributes
MODIFIER_ROSHPIT_STRENGTH_BONUS = 27
MODIFIER_ROSHPIT_AGILITY_BONUS = 28
MODIFIER_ROSHPIT_INTELLIGENCE_BONUS = 29
MODIFIER_ROSHPIT_SPIRIT_BONUS = 30
--Health--
MODIFIER_ROSHPIT_FLAT_HEALTH_BONUS = 31
MODIFIER_ROSHPIT_PERCENT_HEALTH_BONUS = 32
--Mana--
MODIFIER_ROSHPIT_FLAT_MANA_BONUS = 33
MODIFIER_ROSHPIT_PERCENT_MANA_BONUS = 34

-- DMG BONUS --
MODIFIER_ROSHPIT_ITEM_DMG_BONUS = 35
MODIFIER_ROSHPIT_Q_BASE_ABILITY_DMG_BONUS = 36
MODIFIER_ROSHPIT_W_BASE_ABILITY_DMG_BONUS = 37
MODIFIER_ROSHPIT_E_BASE_ABILITY_DMG_BONUS = 38
MODIFIER_ROSHPIT_R_BASE_ABILITY_DMG_BONUS = 39

-- COOLDOWN --
MODIFIER_ROSHPIT_Q_FLAT_CD_MOD = 40
MODIFIER_ROSHPIT_Q_PCT_CD_MOD = 41
MODIFIER_ROSHPIT_Q_MIN_CD_MOD = 42
MODIFIER_ROSHPIT_Q_MAX_CD_MOD = 43

MODIFIER_ROSHPIT_W_FLAT_CD_MOD = 44
MODIFIER_ROSHPIT_W_PCT_CD_MOD = 45
MODIFIER_ROSHPIT_W_MIN_CD_MOD = 46
MODIFIER_ROSHPIT_W_MAX_CD_MOD = 47

MODIFIER_ROSHPIT_E_FLAT_CD_MOD = 48
MODIFIER_ROSHPIT_E_PCT_CD_MOD = 49
MODIFIER_ROSHPIT_E_MIN_CD_MOD = 50
MODIFIER_ROSHPIT_E_MAX_CD_MOD = 51

MODIFIER_ROSHPIT_R_FLAT_CD_MOD = 52
MODIFIER_ROSHPIT_R_PCT_CD_MOD = 53
MODIFIER_ROSHPIT_R_MIN_CD_MOD = 54
MODIFIER_ROSHPIT_R_MAX_CD_MOD = 55

MODIFIER_ROSHPIT_TOOLTIP_Q = 56
MODIFIER_ROSHPIT_TOOLTIP_W = 57
MODIFIER_ROSHPIT_TOOLTIP_E = 58
MODIFIER_ROSHPIT_TOOLTIP_R = 59

--Lowest CD is Jex base Q
GLOBAL_Q_MIN_CD = 0.5
GLOBAL_Q_MAX_CD = 30

GLOBAL_W_MIN_CD = 0
GLOBAL_W_MAX_CD = 10

GLOBAL_E_MIN_CD = 0.1
GLOBAL_E_MAX_CD = 30

GLOBAL_R_MIN_CD = 1
GLOBAL_R_MAX_CD = 120

-- MANA COST --
MODIFIER_ROSHPIT_Q_FLAT_MANA_COST = 56
MODIFIER_ROSHPIT_Q_PCT_MANA_COST = 57

MODIFIER_ROSHPIT_W_FLAT_MANA_COST = 58
MODIFIER_ROSHPIT_W_PCT_MANA_COST = 59

MODIFIER_ROSHPIT_E_FLAT_MANA_COST = 60
MODIFIER_ROSHPIT_E_PCT_MANA_COST = 61

MODIFIER_ROSHPIT_R_FLAT_MANA_COST = 62
MODIFIER_ROSHPIT_R_PCT_MANA_COST = 63

-- CHANNEL TIME --
MODIFIER_ROSHPIT_R_FLAT_CHANNELTIME_MOD = 64
MODIFIER_ROSHPIT_R_PCT_CHANNELTIME_MOD = 65

-- DMG REDUCTION --
MODIFIER_ROSHPIT_PHYSICAL_DMG_REDUCTION = 66
MODIFIER_ROSHPIT_MAGICAL_DMG_REDUCTION = 67
MODIFIER_ROSHPIT_PURE_DMG_REDUCTION = 68

MODIFIER_SPECIAL_TYPE_ON_STUN = 69

-- MASTER STATS TO READ ON CLIENT --
MODIFIER_ROSHPIT_MASTER_AS = 70
MODIFIER_ROSHPIT_MASTER_BASE_ATTACK_DMG = 71
MODIFIER_ROSHPIT_MASTER_GREEN_DMG = 72

-- RANDOM SHIT --
MODIFIER_ROSHPIT_OVERRIDE_ATTACK_EVENT = 73
MODIFIER_ROSHPIT_HP_SHIELD = 74

-- EXP ORBS
RPC_EXP_ORB_1 = 500000
RPC_EXP_ORB_2 = 10000000

--ATTRIBUTES
COLOR_AGILITY ="#2EB82E"
COLOR_STRENGTH = "#CC0000"
COLOR_INTELLIGENCE = "#33CCFF"
COLOR_SPIRIT = "#8847FF"

ROSHPIT_ATTRIBUTE_STRENGTH = 0
ROSHPIT_ATTRIBUTE_AGILITY = 1
ROSHPIT_ATTRIBUTE_INTELLIGENCE = 2
ROSHPIT_ATTRIBUTE_SPIRIT = 3

--ITEMS
RPC_ITEMS_RARITY_COMMON = 1
RPC_ITEMS_RARITY_UNCOMMON = 2
RPC_ITEMS_RARITY_RARE = 3
RPC_ITEMS_RARITY_MYTHICAL = 4
RPC_ITEMS_RARITY_IMMORTAL = 5
RPC_ITEMS_RARITY_ARCANA = 6

RPC_GEAR_SLOT_HEAD = 0
RPC_GEAR_SLOT_WEAPON = 1
RPC_GEAR_SLOT_GLOVES = 2
RPC_GEAR_SLOT_BOOTS = 3
RPC_GEAR_SLOT_BODY = 4
RPC_GEAR_SLOT_TRINKET = 5

RPC_GEAR_SLOT_NAMES = {}
RPC_GEAR_SLOT_NAMES[RPC_GEAR_SLOT_HEAD] = "head"
RPC_GEAR_SLOT_NAMES[RPC_GEAR_SLOT_WEAPON] = "weapon"
RPC_GEAR_SLOT_NAMES[RPC_GEAR_SLOT_GLOVES] = "hands"
RPC_GEAR_SLOT_NAMES[RPC_GEAR_SLOT_BOOTS] = "feet"
RPC_GEAR_SLOT_NAMES[RPC_GEAR_SLOT_BODY] = "body"
RPC_GEAR_SLOT_NAMES[RPC_GEAR_SLOT_TRINKET] = "amulet"

RPC_ITEM_RARITY_COLORS = {}
RPC_ITEM_RARITY_COLORS[RPC_ITEMS_RARITY_COMMON] = "#B0C3D9"
RPC_ITEM_RARITY_COLORS[RPC_ITEMS_RARITY_UNCOMMON] = "#99FF33"
RPC_ITEM_RARITY_COLORS[RPC_ITEMS_RARITY_RARE] = "#4B69FF"
RPC_ITEM_RARITY_COLORS[RPC_ITEMS_RARITY_MYTHICAL] = "#8847FF"
RPC_ITEM_RARITY_COLORS[RPC_ITEMS_RARITY_IMMORTAL] = "#E4AE33"
RPC_ITEM_RARITY_COLORS[RPC_ITEMS_RARITY_ARCANA] = "#ADE55C"

-- CUSTOM MODIFIER_PROPERTIES

MODIFIER_PROPERTY_BASE_ROSHPIT_ARMOR = 1000

-- GAME

RPC_MAX_DAMAGE_MULT_WHEN_PIERCE_EXCEEDS_ARMOR = 1

-- MONSTER
RPC_COLOR_RENDER_BASE_MODEL = 1
RPC_COLOR_RENDER_BASE_AND_WEARABLES = 2

-- AI
RPC_AI_TYPE_CAST_ABILITY1_POSITION = 1
RPC_AI_TYPE_CAST_ABILITY1_NO_TARGET = 2
RPC_AI_TYPE_CAST_ABILITY1_ENEMY = 3
RPC_AI_TYPE_CAST_ABILITY1_ALLY = 4