DJANGHOR_Q1_REGEN_FLAT = 80
DJANGHOR_Q2_ATT = 20000
DJANGHOR_Q2_SELF_MULTIPLE = 10
DJANGHOR_Q3_BUFF_DURATION_INCREASE = 0.08
DJANGHOR_Q3_MAX_APPLY_COUNT = 3

DJANGHOR_W1_DAMAGE_MULT = 0.15
DJANGHOR_W3_ATTACK_PERCENT_ADDED_TO_TORNADO_AND_STOMP = 0.03

DJANGHOR_E2_JINBO_BOOST_IN_LEAP = 0.25
DJANGHOR_E4_DURATION_INCREASE = 0.15

DJANGHOR_R1_ATTACK_POWER_PER_STAT = 0.3

DJANGHOR_GLYPH_4_1_SHIELD_STACKS = 4

DJANGHOR_R1_ARCANA_ATTACK_POWER = 0.2
DJANGHOR_R2_ARCANA_HEALTH_PER_ATTRIBUTE = 0.1

DJANGHOR_WEAP_2_HP_THRESHOLD_PCT = 0.04