DJANGHOR_Q1_REGEN_FLAT = 80
DJANGHOR_Q2_SELF_MULTIPLE = 10
DJANGHOR_Q3_BUFF_DURATION_INCREASE = 0.12

DJANGHOR_W1_DAMAGE_MULT = 0.15
DJANGHOR_W3_ATTACK_PERCENT_ADDED_TO_TORNADO_AND_STOMP = 0.03

DJANGHOR_E2_JINBO_BOOST_IN_LEAP = 0.12
DJANGHOR_E4_DURATION_INCREASE = 0.15