DJANGHOR_Q1_REGEN_FLAT = 0.8
DJANGHOR_Q1_REGEN_PCT = 0.01
DJANGHOR_Q2_ATT = 12
DJANGHOR_Q2_SELF_MULTIPLE = 1.2
DJANGHOR_Q3_BUFF_DURATION_INCREASE = 0.2

DJANGHOR_W1_DAMAGE_MULT = 0.01
DJANGHOR_W2_HEALTH_REGEN_REDUCTION = -12
DJANGHOR_W3_ATTACK_PERCENT_ADDED_TO_TORNADO_AND_STOMP = 0.01
DJANGHOR_W4_NATURE_AMP = 0.12

DJANGHOR_E1_ARMOR_AND_MAGIC_ARMOR_REDUCE = -45
DJANGHOR_E2_JINBO_BOOST_IN_LEAP = 0.02
DJANGHOR_E2_R_FREECAST_STACK_CHANCE = 5
DJANGHOR_E3_CLEANCE_CHANCE = 5
DJANGHOR_E4_DURATION_INCREASE = 0.15

DJANGHOR_BEAR_PHYS_PURE_RED = 0.3
DJANGHOR_WOLF_MAG_PURE_RED = 0.3
DJANGHOR_BIRD_PURE_MAG_BLOCK = 1
DJANGHOR_R1_ATTACK_POWER_PER_STAT = 0.05
DJANGHOR_R2_BONUS_HP = 60
DJANGHOR_R2_LINGER = 25
DJANGHOR_R3_BIRD_BAD_PCT = 1
DJANGHOR_R3_BEAR_ITEM_DAMAGE_PCT = 1
DJANGHOR_R3_LINGER = 15
DJANGHOR_R4_BONUS_ATTRIBUTE = 35
DJANGHOR_R4_LINGER = 25

DJANGHOR_GLYPH_1_1 = 0
DJANGHOR_GLYPH_2_1_CHANCE = 20
DJANGHOR_GLYPH_2_1_BONUS_DAMAGE_PCT = 60
DJANGHOR_GLYPH_2_1_EFFECT_LINGERING = 7
DJANGHOR_GLYPH_3_1_WOLF_EVASION = 35
DJANGHOR_GLYPH_3_1_MONKEY_EVASION = 25
DJANGHOR_GLYPH_4_1_SHIELD_STACKS = 7
DJANGHOR_GLYPH_4_1_DURATION = 12
DJANGHOR_GLYPH_5_1_Q_CD_RED = 3
DJANGHOR_GLYPH_6_1_CLEANCE_INTERVAL = 2
DJANGHOR_GLYPH_7_1_BASH_CHANCE = 25
DJANGHOR_GLYPH_7_1_BASH_BONUS_DAMAGE_PCT = 80
DJANGHOR_GLYPH_7_1_BASH_DURATION = 1.5
DJANGHOR_GLYPH_7_1_ARMOR_LOSS_DURATION = 20
DJANGHOR_GLYPH_7_1_EFFECT_LINGER = 15
DJANGHOR_GLYPH_5_A = 0

DJANGHOR_ARCANA_R_R1_ATTACK_POWER = 0.02
DJANGHOR_ARCANA_R_R2_HEALTH_PER_ATTRIBUTE = 0.1
DJANGHOR_ARCANA_R_R2_LINGER = 25
DJANGHOR_ARCANA_R_R3_RESIST_PCT = 0.012
DJANGHOR_ARCANA_R_R3_RESIST_MAX_PCT = 0.65
DJANGHOR_ARCANA_R_R4_BONUS_ATTRIBUTE = 28
DJANGHOR_ARCANA_R_R4_LINGER = 25

DJANGHOR_IMMORTAL_WEAPON_1_BASE_DMG_PER_AGI  = 3
DJANGHOR_IMMORTAL_WEAPON_2_HP_THRESHOLD_PCT = 0.16

