REDFALL_MITHRIL_NORMAL_MULT = 1
REDFALL_MITHRIL_ELITE_MULT = 2
REDFALL_MITHRIL_LEGEND_MULT = 3
REDFALL_MITHRIL_EQUINOX_MULT = 1.5

REDFALL_MITHRIL_CANYON = 720
REDFALL_MITHRIL_ASHARA = 960
REDFALL_MITHRIL_SHIPYARD = 1200
REDFALL_MITHRIL_CASTLE = 1400
REDFALL_MITHRIL_WORLD_TREE = 1560


--------------
--- FOREST ---
--------------
ROSHPIT_QUEST_REDFALL_HEART_OF_THE_FOREST = 1
ROSHPIT_QUEST_REDFALL_SHRINE_OF_MARU = 2
ROSHPIT_QUEST_REDFALL_CLEANSING_THE_COAST = 3
ROSHPIT_QUEST_REDFALL_AUTUMN_ASH = 4
ROSHPIT_QUEST_REDFALL_SEEKING_ASHARA = 5
ROSHPIT_QUEST_REDFALL_FALLEN_KING_OF_THE_WOLVES = 6

--------------
--- CANYON ---
--------------
ROSHPIT_QUEST_REDFALL_FREEING_THE_WORLD_TREE = 10

----------------
--- FARMLAND ---
----------------
ROSHPIT_QUEST_REDFALL_DEATH_AND_TAXES = 20
ROSHPIT_QUEST_REDFALL_HARVESTING_DUTY = 21

----------------------
--- SHIP GRAVEYARD ---
----------------------




-----------------------
--- CRIMSYTH CASTLE ---
-----------------------
