EKKAN_Q1_DAMAGE = 0.06
EKKAN_Q1_DAMAGE_CHANCE = 10
EKKAN_Q2_BONUS_HP = 0.06
EKKAN_Q3_BASE_ATTACK_DAMAGE_ADDED = 0.3
EKKAN_Q3_MAX_STACKS = 1000
EKKAN_Q3_ARMOR_ADDED = 2
EKKAN_Q4_BONUS_MOVESPEED = 6
EKKAN_Q4_BONUS_ATTACK_SPEED = 6

EKKAN_W1_ATTACK_POWER_MULTIPLE = 0.15
EKKAN_W1_DAMAGE_FLAT = 10
EKKAN_W1_CRIT_DMG = 0.1
EKKAN_W2_DURATION = 1
EKKAN_W2_UNDEAD_AMP = 0.003
EKKAN_W3_BLAST_DAMAGE = 0.1
EKKAN_W3_MOVESPEED_SLOW = 5
EKKAN_W3_MAGIC_ARMOR_LOSS = -50
EKKAN_W4_MAGIC_ARMOR = 120
EKKAN_W4_PIERCES = 100

EKKAN_E1_CORPSE_HP_TO_EXPLOSION = 0.005
EKKAN_E1_RANGE_BASE = 700
EKKAN_E1_RANGE = 5
EKKAN_E2_HP_MULT = 0.5
EKKAN_E2_FAMILIAR_ATTACK = 0.05
EKKAN_E2_FAMILIAR_ROSHPIT_ATTRIBUTES = 0.05
EKKAN_E3_ARMOR_REDUCTION = -120
EKKAN_E4_STUN_DURATION = 0.35
EKKAN_E4_HP_REGEN = 0.01

EKKAN_R1_LIFESTEAL = 0.005
EKKAN_R2_DAMAGE = 0.005
EKKAN_R3_DAMAGE = 0.1
EKKAN_R4_MULTICAST_CHANCE = 20

EKKAN_ARCANA_Q1_DAMAGE = 0.02
EKKAN_ARCANA_Q1_MOVESPEED_SLOW = 30
EKKAN_ARCANA_Q2_BASE_ATTACK_DAMAGE = 14
EKKAN_ARCANA_Q2_BONUS_MOVESPEED = 1
EKKAN_ARCANA_Q2_ARMOR_LOSS = -70
EKKAN_ARCANA_Q2_POISON_PER_ATTACK = 1
EKKAN_ARCANA_Q3_BASE_ATTACK_DAMAGE = 0.2
EKKAN_ARCANA_Q3_ARMOR = 1
EKKAN_ARCANA_Q3_MAX_STACKS = 1000
EKKAN_ARCANA_Q4_BONUS_DAMAGE_AURA = 0.06
EKKAN_ARCANA_Q4_ARMOR_AURA = 100

-- CRUXYS ARCANAS

EKKAN_ARCANA_W1A_BASE_DURATION = 1
EKKAN_ARCANA_W1A_DURATION = 0.1
EKKAN_ARCANA_W1A_DAMAGE_PCT_ARMOR = 2
EKKAN_ARCANA_W1A_DAMAGE_INTERVAL = 1
EKKAN_ARCANA_W2A_DAMAGE_INTERVAL = 0.5
EKKAN_ARCANA_W2A_RADIUS = 220
EKKAN_ARCANA_W2A_DAMAGE_PCT_MAX_HEALTH = 1
EKKAN_ARCANA_W2A_MOVESLOW = -2.5
EKKAN_ARCANA_W3A_RADIUS = 280
EKKAN_ARCANA_W3A_DURATION = 7
EKKAN_ARCANA_W3A_DAMAGE_PCT_ARMOR_PIERCE = 8
EKKAN_ARCANA_W3A_ARMOR_REDUCTION = -100
EKKAN_ARCANA_W3A_DAMAGE_INTERVAL = 1
EKKAN_ARCANA_W4A_DURATION_INCREASE = 4
EKKAN_ARCANA_W4A_ELEMENTAL_AMP = 15

EKKAN_ARCANA_W1B_CHANCE = 20
EKKAN_ARCANA_W1B_RADIUS = 320
EKKAN_ARCANA_W1B_BASE_DURATION = 0.3
EKKAN_ARCANA_W1B_ROOT_DURATION = 0.01
EKKAN_ARCANA_W1B_DAMAGE_PCT_MAGIC_ARMOR = 2
EKKAN_ARCANA_W2B_CHANCE = 12
EKKAN_ARCANA_W2B_SPEAR_COUNT = 3
EKKAN_ARCANA_W2B_DMG_PCT_ATK_POWER = 2
EKKAN_ARCANA_W2B_BASE_RADIUS = 300
EKKAN_ARCANA_W2B_RADIUS = 5
EKKAN_ARCANA_W3B_DAMAGE_DELAY = 0.35
EKKAN_ARCANA_W3B_RADIUS = 450
EKKAN_ARCANA_W3B_DMG_SPELL_PIERCE = 8
EKKAN_ARCANA_W3B_PCT_MOVE_SLOW = -2.5
EKKAN_ARCANA_W3B_PCT_SLOW_DURATION = 5
EKKAN_ARCANA_W4B_DURATION_INCREASE = 4
EKKAN_ARCANA_W4B_ELEMENTAL_AMP = 15

EKKAN_ARCANA_W1C_RANGE = 1000
EKKAN_ARCANA_W1C_ATTACK_DAMAGE = 4
EKKAN_ARCANA_W1C_ATTACK_SPEED = 0.1
EKKAN_ARCANA_W2C_RADIUS = 220
EKKAN_ARCANA_W2C_DAMAGE_INTERVAL = 0.5
EKKAN_ARCANA_W2C_BURN_DAMAGE = 1.5
EKKAN_ARCANA_W2C_BONUS_ARMOR = 120
EKKAN_ARCANA_W3C_RADIUS = 240
EKKAN_ARCANA_W3C_IMPACT_DMG = 8
EKKAN_ARCANA_W3C_RANGE_BASE = 500
EKKAN_ARCANA_W3C_RANGE = 10
EKKAN_ARCANA_W4C_DURATION_INCREASE = 4
EKKAN_ARCANA_W4C_ELEMENTAL_AMP = 15

EKKAN_GLYPH_1_1_ADD_UNITS = 4

EKKAN_GLYPH_2_1_E_SPAWN_CORPSES = 5

EKKAN_GLYPH_3_1_SKELETON_DURATION_INCREASE_PCT = 100

EKKAN_GLYPH_4_1_R_AS_INCREASE = 60
EKKAN_GLYPH_4_1_R_MS_INCREASE = 80
EKKAN_GLYPH_4_1_BUFF_DURATION = 15

EKKAN_GLYPH_5_1_Q_ADD_UNITS = 2

EKKAN_GLYPH_6_1_E_ADD_UNITS = 1

EKKAN_GLYPH_7_1_R3_MORE_TARGETS = 2

EKKAN_GLYPH_5_A_LEASH_RANGE_INCREASE = 1000

EKKAN_GLYPH_5_a_STACKS = 10

EKKAN_IMMORTAL_WEAPON_1_BASE_DAMAGE = 800
EKKAN_IMMORTAL_WEAPON_1_MAX_STACKS = 6
EKKAN_IMMORTAL_WEAPON_1_DURATION = 10

EKKAN_IMMORTAL_WEAPON_2_FAMILIAR_PURE_UNDEAD_ATTACK_PCT = 10

EKKAN_IMMORTAL_WEAPON_3_AMP = 3
