REDFALL_MITHRIL_NORMAL_MULT = 1
REDFALL_MITHRIL_ELITE_MULT = 2
REDFALL_MITHRIL_LEGEND_MULT = 6
REDFALL_MITHRIL_EQUINOX_MULT = 3

REDFALL_MITHRIL_CANYON = 80
REDFALL_MITHRIL_ASHARA = 35
REDFALL_MITHRIL_SHIPYARD = 260
REDFALL_MITHRIL_CASTLE = 520
REDFALL_MITHRIL_WORLD_TREE = 800
