REDFALL_MITHRIL_NORMAL_MULT = 1
REDFALL_MITHRIL_ELITE_MULT = 2
REDFALL_MITHRIL_LEGEND_MULT = 6
REDFALL_MITHRIL_EQUINOX_MULT = 3

REDFALL_MITHRIL_CANYON = 180
REDFALL_MITHRIL_ASHARA = 180
REDFALL_MITHRIL_SHIPYARD = 300
REDFALL_MITHRIL_CASTLE = 350
REDFALL_MITHRIL_WORLD_TREE = 390
