REDFALL_MITHRIL_NORMAL_MULT = 1
REDFALL_MITHRIL_ELITE_MULT = 2
REDFALL_MITHRIL_LEGEND_MULT = 3
REDFALL_MITHRIL_EQUINOX_MULT = 1.5

REDFALL_MITHRIL_CANYON = 720
REDFALL_MITHRIL_ASHARA = 720
REDFALL_MITHRIL_SHIPYARD = 1200
REDFALL_MITHRIL_CASTLE = 1400
REDFALL_MITHRIL_WORLD_TREE = 1560
