ABLECORE_GREAVES_MS_REQ = 300
ABLECORE_GREAVES_POST_MITI = 600
ABLECORE_GREAVES_DMG_RED = 80
ABLECORE_GREAVES_STICKY_DURATION = 6

DUNETREADS_CD_RED = 2

BLADESLINGER_ATT_INTERVAL = 0.2

MOON_TECHS_MS_SLOW_PCT = 50
MOON_TECHS_RADIUS = 580
MOON_TECHS_DURATION = 9

VOYAGER_BOOTS_E_RED = 30

TRANQUIL_BOOTS_HP_HEAL_PCT = 10
TRANQUIL_BOOTS_DISTANCE = 200

MANA_STRIDERS_MANA_RESTORE_PCT = 3
MANA_STRIDERS_DISTANCE = 240

ADMIRAL_BOOTS_BAD_E = 100

ROOTED_FEET_ARMOR_AMP = 2
ROOTED_FEET_HP_REGEN_AMP = 3
ROOTED_FEET_DMG_REDUCTION = 50

CRUSADER_BOOTS_STR_TO_ARMOR_AURA_PCT = 10
CRUSADER_BOOTS_AURA_RANGE = 800

ARCANYS_SLIPPER_NUMBER_OF_EXPLOSIONS = 3
ARCANYS_SLIPPER_EXPLOSIONS_DURATION  = 1.2
ARCANYS_SLIPPER_MANA_DRAIN_PER_EXPLOSION_PCT = 10
ARCANYS_SLIPPER_BASE_ATTACK_FOR_MANA_DRAIN = 10
ARCANYS_SLIPPER_BUFF_DURATION = 10

REDROCK_NUMBER_OF_PULSES = 3
REDROCK_DURATION_OF_PULSES = 1.5
REDROCK_TAUNT_DURATION = 5
REDROCK_HP_INCREASE_PCT = 200
REDROCK_DAMAGE_REDUCTION_PCT = 50
REDROCK_TAUNT_RADIUS = 600

PATHFINDER_DElAY = 7
PATHFINDER_HP_RESTORE_PCT = 8
PATHFINDER_MANA_RESTORE_PCT = 4

BLUE_DRAGON_GREAVES_DISTANCE = 1200
BLUE_DRAGON_GREAVES_EVASION = 85
BLUE_DRAGON_GREAVES_BONUS_ATTACK_DAMAGE = 350
BLUE_DRAGON_GREAVES_DURATION = 7

RESPLENDENT_RUBBER_DMG_REDUCTION = 75

OLD_WISDOM_BAD = 650
OLD_WISDOM_COOLDOWN = 12

PURE_WATERS_MANA_RESTORE_PCT = 4
PURE_WATERS_ATTACK_TO_DMG = 10
PURE_WATERS_INT_TO_DMG = 80
PURE_WATERS_SLOW = 30
PURE_WATERS_SLOW_DURATION = 4
PURE_WATERS_INTERVAL_RESTRICTION = 1

TERRASIC_LAVA_BOOTS_BONUS_ATTACK_DMG = 100
TERRASIC_LAVA_BOOTS_BONUS_ATTACK_SPEED = 200
TERRASIC_LAVA_BOOTS_BONUS_ATTACK_RANGE = 150
TERRASIC_LAVA_BOOTS_DURATION = 7

GIANT_HUNTERS_BOOTS_IMMUNITY_DURATION = 3.5

REDFALL_RUNNERS_BAD_MULT = 2400
REDFALL_RUNNERS_DURATION = 7

BOOTS_OF_ASHARA_BAD_E = 20
BOOTS_OF_ASHARA_HP_THRESHOLD = 50

SANDSTREAM_INTERVAL = 12
SANDSTREAM_MAX_STACKS = 2

CRIMSYTH_ELITE_ARMOR = 50
CRIMSYTH_ELITE_MAGIC_RESISTANCE = 85
CRIMSYTH_ELITE_DURATION = 3

BOOTS_OF_GREAT_FORTUNE_CHANCE_INCREASE = 10
BOOTS_OF_GREAT_FORTUNE_TRICKSTER_BOOST = 2

BLOODSTONE_BOOTS_HP_TRESHOLD_PCT = 35
BLOODSTONE_BOOTS_E_CD = 1

ALARANA_MAGIC_POST_MITI = 75
ALARANA_ICE_ENCASE_DURATION = 8
ALARANA_DAMAGE_BLOCK_THRESHOLD_OF_MAX_HP = 4
ALARANA_EXPLOSION_DAMAGE_OF_MAX_HP = 100
ALARANA_EXPLOSION_RADIUS = 600
ALARANA_ENEMY_FREEZE_DURATION = 3.0

EMERALD_SPEED_MS_LOW_CAP = 600

RED_OCTOBER_DMG_REDUCTION = 50

STEAMBOOTS_AGI_TO_ITEM_DAMAGE = 0.3
STEAMBOOTS_AGI_DIVISOR = 10

OCEANRUNNER_AGI_TO_BAD = 0.25
OCEANRUNNER_AGI_DIVISOR = 10

CRYSTALLINE_DAMAGE_REDUCTION_FROM_ROOTED = 80
CRYSTALLINE_PRE_MITI_AMP = 5

GRAVELFOOT_DEBUFF_CLEANCE_INTERVAL = 0.65
GRAVELFOOT_SELF_SLOW_DURATION = 3
GRAVELFOOT_SELF_SLOW = 200
GRAVELFOOT_DMG_REDUCTION = 99.5

ICE_FLOE_TRAVEL_DISTANCE = 1500

PACE_OF_STORM_RADIUS = 700
PACE_OF_STORM_COOLDOWN = 1
PACE_OF_STORM_MIN_AMP = 0.4
PACE_OF_STORM_MAX_AMP = 4
PACE_OF_STORM_STEADFAST_THRESHOLD = 10
PACE_OF_STORM_MEGASTEADFAST_THRESHOLD = 30

SANGE_HP_PER_AGI = 25
SANGE_MP_PER_AGI = 5

YASHA_AS_PER_STR = 20
YASHA_BAT = 1.1

PEGASUS_MAX_MS_AMP_PCT = 30
PEGASUS_E_SPEED_PCT = 100

PIVOT_BOOT_MAX_MS = 850
PIVOT_BOOT_MS = 400
PIVOT_BURST_DURATION = 4