BARON_STORM_MAX_TARGETS = 6
BARON_STORM_DMG_RESISTANCE = 0.85
BARON_STORM_DMG_PER_ATT = 5
BARON_STORM_DUR = 5
BARON_STORM_COOLDOWN = 0.1
BARON_STORM_SEARCH_RADIUS = 500

HURRICANE_VEST_MAX_DISTANCE = 1800
HURRICANE_VEST_DMG_AMP = 10
HURRICANE_VEST_DMG_EXP_SCALE = 3
HURRICANE_VEST_MSP_REDUCE = 150
HURRICANE_VEST_ATT_SPD_REDUCE = 150
HURRICANE_VEST_SLOW_DUR = 5
HURRICANE_VEST_HURRICANE_SPEED = 1000
HURRICANE_VEST_HURRICANE_COUNT = 16

ROBE_OF_FLOODING_MANA_RESTORE_PCT = 5
ROBE_OF_FLOODING_DURATION = 12
ROBE_OF_FLOODING_AOE_INT_TO_DMG = 35
ROBE_OF_FLOODING_AOE_RADIUS = 340
ROBE_OF_FLOODING_ATTACK_TO_WAVE_DMG = 1
ROBE_OF_FLOODING_ENEMY_SEARCH_RANGE = 1000

AVALANCHE_PLATE_AVALANCHE_RADIUS = 420
AVALANCHE_PLATE_AVALANCHE_STR_TO_DMG = 15
AVALANCHE_PLATE_AVALANCHE_INTERVAL = 0.2
AVALANCHE_PLATE_STUN_DUR = 0.1
AVALANCHE_PLATE_ENEMY_HITS_THRESHOLD = 20
AVALANCHE_PLATE_EARTHQUAKE_STR_TO_DMG = 80
AVALANCHE_PLATE_EARTHQUAKE_RADIUS = 800
AVALANCHE_PLATE_EARTHQUAKE_STUN_DUR = 1.6
AVALANCHE_PLATE_ITEM_AMP_PER_STR = 0.3
AVALANCHE_PLATE_STR_DIVISOR = 10

VIOLET_GUARD_ARMOR_BAD = 350
VIOLET_GUARD_ARMOR_DAMAGE_TO_ARMOR_REDUCTION = 0.001
VIOLET_GUARD_ARMOR_DURATION = 6

SERAPHIC_SOULVEST_ATTACK_TO_DMG = 50
SERAPHIC_SOULVEST_RADIUS_OF_SEARCH = 1600

WATCHER_I_REFRESH_CHANCE = 25
WATCHER_II_BAD = 150

SORCERERS_REGALIA_MAGIC_POST_MITI = 40

SPELLSLINGER_MANA_RESTORE = 35
SPELLSLINGER_BAD = 100

ICE_QUILL_MANA_THRESHOLD = 600
ICE_QUILL_INTERVAL = 0.1
ICE_QUILL_MANA_RESTORE_PCT = 1
ICE_QUILL_ATTACK_TO_DMG = 4
ICE_QUILL_RADIUS = 460

FEATHERWHITE_HEAL_OF_MAX_HP = 6
FEATHERWHITE_MAGIC_AND_PURE_REDUCTION = 30
FEATHERWHITE_AURA_RADIUS = 640
FEATHERWHITE_INTERVAL = 0.5

DRAGON_CEREMONY_NUMBER_OF_ENEMIES = 12
DRAGON_CEREMONY_INTERVAL = 0.8
DRAGON_CEREMONY_PRIMARY_ATT_TO_DMG = 12
DRAGON_CEREMONY_RADIUS = 820

SECRET_TEMPLE_SHIELDS = 7
SECRET_TEMPLE_SHIELDS_DURATION = 30

VAMPIRIC_BREASTPLATE_Q_LIFESTEAL = 30

DARK_ARTS_INT_TO_AGI = 0.8

LEGION_VESTMENTS_ATTRIBUTE_INCREASE = 0.3

NIGHTMARE_RIDER_SLOW = 40
NIGHTMARE_RIDER_ARMOR_REDUCTION = 80
NIGHTMARE_RIDER_DEBUFF_DURATION = 10
NIGHTMARE_RIDER_POST_MITIGATION_DEBUFF = 600
NIGHTMARE_RIDER_RADIUS = 400
NIGHTMARE_RIDER_RADIUS_INCREASE = 100
NIGHTMARE_RIDER_ELEMENT_SHADOW_INCREASE = 300
NIGHTMARE_RIDER_MAX_STACKS = 20

WATER_MAGE_ROBES_ATTACK_TO_DMG = 7
WATER_MAGE_ROBES_INT_TO_DMG = 30
WATER_MAGE_ROBES_MS_SLOW = 50
WATER_MAGE_ROBES_SLOW_DURATION = 4
WATER_MAGE_ROBES_POST_MITI_AMP = 100

DEPTH_CREST_ARMOR_CHANCE = 30
DEPTH_CREST_ARMOR_STUN_DURATION = 0.1
DEPTH_CREST_ARMOR_STUN_RADIUS = 300
DEPTH_CREST_ARMOR_STR_TO_DMG = 120
DEPTH_CREST_ARMOR_ARMOR_TO_DMG = 8000
DEPTH_CREST_ARMOR_ITEM_AMP = 0.4
DEPTH_CREST_ARMOR_STR_DIVISOR = 10

RADIANT_RUINS_LEATHER_AS = 220
RADIANT_RUINS_LEATHER_MS = 120

SPACE_TECH_AS_SLOW = 180
SPACE_TECH_MS_SLOW = 50
SPACE_TECH_DURATION = 8
SPACE_TECH_BONUS_ATTACK_DMG_PER_STACK = 35
SPACE_TECH_BUFF_DURATION = 10
SPACE_TECH_GAIN_INTERVAL = 0.3
SPACE_TECH_RADIUS = 640

GILDED_SOUL_CAGE_HEAL_PCT = 15
GILDED_SOUL_CAGE_HEAL_RADIUS = 240
GILDED_SOUL_CAGE_BONUS_ATTACK_DAMAGE = 4
GILDED_SOUL_CAGE_ELEMENT_HOLY_AMP = 10
GILDED_SOUL_CAGE_BUFF_DURATION = 8
GILDED_SOUL_CAGE_MAX_STACKS = 100
GILDED_SOUL_CAGE_MAGIC_IMMUNITY_DURATION = 4

STORMSHIELD_PHYS_REDUCTION = 0.5

HERMIT_SPIKE_THRESHOLD = 15
HERMIT_SPIKE_DAMAGE_OF_DAMAGE_TAKEN = 30
HERMIT_SPIKE_RADIUS = 550

SOLAR_CAPE_BAD_AND_ELEMENTAL_AMP = 400
SOLAR_CAPE_DURATION = 15

OCEAN_TEMPEST_MANA_DRAIN_PER_SECOND = 40
OCEAN_TEMPEST_MANA_DRAIN_THRESHOLD = 100
OCEAN_TEMPEST_BAD_PER_MANA_THRESHOLD = 1.5

TWILIGHT_VESTMENT_HP_THRESHOLD = 20
TWILIGHT_VESTMENT_HEAL_PCT = 75
TWILIGHT_VESTMENT_DELAY = 0.05

WINDSTEEL_EVASION = 50
WINDSTEEL_MOVESPEED = 100
WINDSTEEL_DURATION = 8
WINDSTEEL_COOLDOWN = 5

BLADESTORM_NUMBER_OF_ATTACKS = 10
BLADESTORM_BONUS_ATTACK_DMG = 100
BLADESTORM_POST_MITI = 200
BLADESTORM_MAX_STACKS = 3

TERRASIC_STONE_PLATE_POST_MITI = 200

GOLDEN_WARPLATE_PHYS_POST_MITI_AMP = 700
GOLDEN_WARPLATE_MAGIC_OUTPUT_REDUCTION = 65

GOLD_PLATE_OF_LEON_PRIMARY_ATTRIBUTE_INCREASE = 50

STAGGERING_KNIGHT_CRUSHER_STUN_DURATION_INCREASE = 50
STAGGERING_KNIGHT_CRUSHER_STUN_IMMUNITY_COUNTER_DECREASE = 50

SAPPHIRE_DRAGON_SCALE_ATTACK_PER_INT = 20
SAPPHIRE_DRAGON_SCALE_ARMOR_PER_INT = 0.4
RUBY_DRAGON_SCALE_ATTACK_PER_STR = 20
RUBY_DRAGON_SCALE_ARMOR_PER_STR = 0.4
TOPAZ_DRAGON_SCALE_ATTACK_PER_AGI = 20
TOPAZ_DRAGON_SCALE_ARMOR_PER_AGI = 0.4

SACRED_TRIALS_ARMOR_ATTACK_TO_DMG = 1000
SACRED_TRIALS_ARMOR_AOE_RADIUS = 320

GUARD_OF_FERONIA_SHIELD_DURATION_E = 1.5
GUARD_OF_FERONIA_SHIELD_DURATION_R = 4.5
GUARD_OF_FERONIA_SHIELD_DAMAGE_REDUCTION = 95

MYSTIC_MANA_WALL_MAGIC_PURE_REDUCTION = 75
MYSTIC_MANA_WALL_MANA_TO_ARMOR = 30 
MYSTIC_MANA_WALL_ARMOR_DIVISOR = 1

VERMILLION_DREAM_CAST_RANGE_INCREASE = 900

ANCIENT_TANARI_WIND_RADIUS = 500
ANCIENT_TANARI_WIND_MS_REDUCTION = 80
ANCIENT_TANARI_WIND_AS_REDUCTION = 100
ANCIENT_TANARI_WIND_MISS_CHANCE = 30

BLAZING_FURY_AGI_TO_STR_AND_INT = 45

OUTLAND_STONE_BAD = 2700
OUTLAND_STONE_SELF_STUN = 1.5

DIREWOLF_BULWARK_PRIMARY_ATT_DIVISOR = 10
DIREWOLF_BULWARK_BASE_ATTACK_DMG = 20
DIREWOLF_BULWARK_ARMOR = 1
DIREWOLF_BULWARK_BAD = 0.1

ARMOR_OF_ATLANTIS_DMG_REDUCTION_LETHAL_BLOW_PCT = 70
ARMOR_OF_ATLANTIS_DMG_REDUCTION_PCT_PER_MISSING_HP_PCT = 1.5
ARMOR_OF_ATLANTIS_MAX_DMG_REDUCTION_PCT = 81

SKYFORGE_DMG_REDUCTION = 30

TEMPLAR_LIGHT_SEER_HP_PCT_PER_TICK = 20
TEMPLAR_LIGHT_SEER_TICKRATE = 0.15
TEMPLAR_LIGHT_SEER_MAX_STACKS = 20

EMPYREAL_SUNRISE_ROBE_LOWEST_ATT_AMP = 1.6

SEA_GIANTS_PLATE_DMG_REDUCTION_WHILE_STUNNED = 96

BOREAL_GRANITE_VEST_CHANCE = 10

CAPTAINS_VEST_Q1 = 3
CAPTAINS_VEST_Q2 = 6
CAPTAINS_VEST_Q3 = 15
CAPTAINS_VEST_Q4 = 30
CAPTAINS_VEST_W1 = 3
CAPTAINS_VEST_W2 = 6
CAPTAINS_VEST_W3 = 15
CAPTAINS_VEST_W4 = 30
CAPTAINS_VEST_E1 = 3
CAPTAINS_VEST_E2 = 6
CAPTAINS_VEST_E3 = 15
CAPTAINS_VEST_E4 = 30
CAPTAINS_VEST_R1 = 1
CAPTAINS_VEST_R2 = 2
CAPTAINS_VEST_R3 = 5
CAPTAINS_VEST_R4 = 10
CAPTAINS_VEST_INTERNAL_MULTIPLIER_OF_STACKS =  5

TATTERED_NOVICE_INTERVAL = 12
TATTERED_NOVICE_MAX_STACKS = 2

ERUDITE_TEACHER_HEALTH_MULT = 5
ERUDITE_TEACHER_ATTACK_MULT = 10
ERUDITE_TEACHER_ARMOR_MULT = 10

ALIEN_ARMOR_OUTGOING_DAMAGE_MULT = 500
ALIEN_ARMOR_INCOMING_DAMAGE_REDUCTION = 90
ALIEN_ARMOR_ILLUSION_DURATION = 10
ALIEN_ARMOR_ILLUSION_AS = 1000
ALIEN_ARMOR_RESPAWN_DELAY = 3

NETHERGRASP_MAX_LINKS = 5
NETHERGRASP_BREAK_DISTANCE = 1600
NETHERGRASP_LINK_RANGE = 1200
NETHERGRASP_ATTACK_INTERVAL = 0.15