BLUE_RAIN_CHANCE = 15
BLUE_RAIN_DMG_PER_ATT = 75

ELDER_GRASP_HEAL_PCT = 0.1
ELDER_GRASP_RADIUS = 500
ELDER_GRASP_SHIELD_PER_HP = 3

STORMCLOTH_COOLDOWN = 6
STORMCLOTH_STUN_DUR = 1.5
STORMCLOTH_STUN_AOE = 900