BLUE_RAIN_CHANCE = 15
BLUE_RAIN_DMG_PER_ATT = 75

ELDER_GRASP_HEAL_PCT = 0.1
ELDER_GRASP_RADIUS = 500
ELDER_GRASP_SHIELD_PER_HP = 3

BERSERKER_GLOVES_ATTACK_DMG_PER_LVL_PER_STACK = 200
BERSERKER_GLOVES_ATTACK_SPEED_PER_STACK = 30
BERSERKER_GLOVES_DURATION = 12
BERSERKER_GLOVES_DAMAGE_RECEIVED_INCREASE =  5
BERSERKER_GLOVES_STACKS_PENALTY = 25

SHADOW_ARMLET_HEAL_CHANCE = 15

HIGH_FLAME_GAUNTLET_CHANCE = 20
HIGH_FLAME_GAUNTLET_ATTACK_TO_DMG = 150
HIGH_FLAME_GAUNTLET_ARMOR_TO_DMG = 25
HIGH_FLAME_GAUNTLET_ATTACK_TO_DMG_FIREBALL = 250
HIGH_FLAME_GAUNTLET_STUN_DUR = 1.6

CLAW_OF_AZINOTH_DAMAGE_AMP = 50

LIVING_GAUNTLET_MANA_THRESHOLD = 25
LIVING_GAUNTLET_DMG_REDUCTION = 50
LIVING_GAUNTLET_HP_REGEN_PCT = 1

SPIRIT_GLOVE_INT_TO_HEAL = 7
SPIRIT_GLOVE_HEAL_INTERVAL = 1
SPIRIT_GLOVE_DURATION = 12
SPIRIT_GLOVE_RADIUS = 600

SHADOWFLAME_FIST_MANA_CAP = 10
SHADOWFLAME_FIST_W_BAD = 1200

AQUASTEEL_CHANCE = 20
AQUASTEEL_ATTACK_TO_DMG = 8
AQUASTEEL_ARMOR_TO_DMG = 10
AQUASTEEL_STUN_DUR = 1.5

GRAVEKEEPER_MAX_STACKS_PER_SEC = 8
GRAVEKEEPER_PRE_MITI_DAMAGE_AMP_PER_STACK = 0.1
GRAVEKEEPER_MOVESPEED_DRAIN = 3

STORMCLOTH_COOLDOWN = 6
STORMCLOTH_STUN_DUR = 1.5
STORMCLOTH_STUN_AOE = 900

CHITINOUS_LOBSTER_CLAW_DMG_RED_PER_STACK = 0.01
CHITINOUS_LOBSTER_CLAW_MAX_STACKS = 92
CHITINOUS_LOBSTER_CLAW_STACK_RATE = 0.2

CYTOPIAN_LASER_DMG_PER_ATT = 3
CYTOPIAN_LASER_MAX_STACKS = 10
CYTOPIAN_LASER_RADIUS = 750

MOUNTAIN_VAMBRACES_CHANCE = 15
MOUNTAIN_VAMBRACES_STUN_DURATION = 2
MOUNTAIN_VAMBRACES_STUN_RADIUS = 290
MOUNTAIN_VAMBRACES_DAMAGE_PER_STR = 1500
MOUNTAIN_VAMBRACES_ITEM_AMP_PER_STR = 0.3
MOUNTAIN_VAMBRACES_STR_DIVISOR = 10

FARSEER_PRE_MITI_MAGIC_BASE = 0.01
FARSEER_DURATION = 15
FARSEER_PRIMARY_ATT_CAP = 50

MORDIGGUS_GAUNTLET_POSTMIT_PCT_PER_HP_PCT_MISSING = 6
MORDIGGUS_GAUNTLET_HP_DRAIN_PCT_ON_SPELL = 20
MORDIGGUS_GAUNTLET_HP_DRAIN_PCT_ON_ATTACK = 7
MORDIGGUS_GAUNTLET_MIN_HP_PCT = 30

HALCYON_SOUL_GLOVE_BONUS = 0.5
HALCYON_SOUL_GLOVE_BASE_DAMAGE_PER_ATT = 5

IRONBOUND_GLOVES_ATTACK_PER_ARMOR = 12

SWEEPING_WIND_BONUS_DAMAGE_PER_STACK_PCT = 100
SWEEPING_WIND_ATT_POWER_TO_DAMAGE_PCT = 150
SWEEPING_WIND_RADIUS = 400
SWEEPING_WIND_MAX_STACKS = 5
SWEEPING_WIND_DURATION = 30

GOLDBREAKER_DEBUFF_DURATION = 7

GAUNTLET_OF_DIVINE_PURITY_MULTIPLIER = 20

SCARECROW_GLOVES_MPREGEN_PER_INT = 0.5

MASTER_GLOVES_BAD = 200

PHOENIX_GLOVES_HP_REGEN_PER_MISSING_HP = 0.15
PHOENIX_GLOVES_ATT_DMG_PER_HP = 1

FROSTBURN_GLOVES_MS_SLOW = 100
FROSTBURN_GLOVES_MS_SLOW_DUR = 4
FROSTBURN_GLOVES_EXPLOSION_RADIUS = 240
FROSTBURN_GLOVES_CHANCE = 20

POWER_RANGER_BONUS_DAMAGE = 250
POWER_RANGER_PHYS_POST_MITI = 200

GRAND_ARCANIST_BAD_PER_INT = 0.0003

SILVERSPRING_BASE_DMG_PER_REGEN = 10

ROYAL_WRISTGUARDS_BONUS_DMG_PCT = 20
ROYAL_WRISTGUARDS_Q_BAD = 20
ROYAL_WRISTGUARDS_CHARGE_CAP = 80
ROYAL_WRISTGUARDS_STACK_DURATION = 15

FORGOTTEN_GHOST_DOT_MULT = 2.4

SPIRITUAL_EMPOWERMENT_TICKRATE = 6.0
SPIRITUAL_EMPOWERMENT_BAD = 80
SPIRITUAL_EMPOWERMENT_MAX_STACKS = 10

AUTUMNROCK_BRACER_CHANCE = 10
AUTUMNROCK_BRACER_STUN_DUR = 2
AUTUMNROCK_BRACER_DMG_PER_STR = 200
AUTUMNROCK_BRACER_ITEM_DAMAGE_AMP_PER_HP_PCT = 0.1
AUTUMNROCK_BRACER_ITEM_DAMAGE_HP_DIVISOR = 100
AUTUMNROCK_BRACER_EXP_AOE = 160

SKULLDIGGER_STACK_RATE = 1.2
SKULLDIGGER_ATTACK_POWER_TO_DAMAGE = 75
SKULLDIGGER_STUN_DURATION = 0.9
SKULLDIGGER_MAX_STACKS = 9

ETHEREAL_REVENANT_CHANCE = 11
ETHEREAL_REVENANT_DAMAGE_REDUCTION_PCT = 90
ETHEREAL_REVENANT_DAMAGE_AMP = 3
ETHEREAL_REVENANT_DURATION = 6

DEPTH_DEMON_CLAW_AUGMENT_REDUCTION = 0.3

DEMONFIRE_ELEMENTAL_AMP_PCT = 30
DEMONFIRE_NUMBER_ENEMIES = 4
DEMONFIRE_STACKS = 25
DEMONFIRE_STACK_DURATION = 6
DEMONFIRE_RADIUS = 1000
DEMONFIRE_DAMAGE_PER_ATTACK_PER_STACK = 1

SPELLFIRE_CAST_POINT_REDUCTION = 80

HEAVY_ECHO_REPEATS = 2

HAND_OF_MIDAS_CHANCE = 20
HAND_OF_MIDAS_ATTACK_DAMAGE_MULT = 50
HAND_OF_MIDAS_RADIUS = 340
HAND_OF_MIDAS_FREEZE_DURATION = 2
HAND_OF_MIDAS_FREEZE_CD = 5

DARK_EMISSARY_ROOT_DURATION = 5
DARK_EMISSARY_RADIUS = 400
DARK_EMISSARY_DAMAGE_MULT = 240
DARK_EMISSARY_INVIS_DURATION = 2
DARK_EMISSARY_INVIS_CD = 8

BUZUKIS_FINGER_POST_MITI = 500
BUZUKIS_FINGER_MODIFIER_ATTACK_PCT = 100
BUZUKIS_FINGER_DURATION = 30
BUZUKIS_FINGER_RADIUS = 500

SWIFTSPIKE_BAD_PER_MS = 0.01
