BASILISK_PLAGUE_PHYSICAL_POSTMIT = 15
BASILISK_PLAGUE_MOVESPEED_REDUCE_PCT = 50
BASILISK_PLAGUE_ATT_SPD_REDUCE = 240
BASILISK_PLAGUE_TIME_BEFORE_STONE_FORM = 2
BASILISK_PLAGUE_THINK_INTERVAL = 0.5
BASILISK_PLAGUE_STONE_FORM_DUR = 2

KABUTO_SHIELD_DUR = 4
KABUTO_SHIELD_RESISTANCE = 0.95

LAVA_FORGE_DMG_PER_ATT = 2
LAVA_FORGE_DMG_PER_AGI = 2000
LAVA_FORGE_RADIUS = 240

SHIPYARD_SHIELD_COOLDOWN = 0.1

IRON_COLOSSUS_ATT_PER_STR = 10
IRON_COLOSSUS_AMR_PER_STR = 0.5
IRON_COLOSSUS_DMG_PER_ATT = 50
IRON_COLOSSUS_ATT_SPD = 120
IRON_COLOSSUS_ATT_RNG = 180

STORMCRACK_ATTACK_DAMAGE_MULT = 20
STORMCRACK_ATTR_DAMAGE_MULT = 200

HELM_OF_THE_MOUNTAIN_GIANT_PERCENT_HEALTH = 200
HELM_OF_THE_MOUNTAIN_GIANT_PERCENT_DAMAGE_REDUCTION = 50
