BASILISK_PLAGUE_PHYSICAL_POSTMIT = 15
BASILISK_PLAGUE_MOVESPEED_REDUCE_PCT = 50
BASILISK_PLAGUE_ATT_SPD_REDUCE = 240
BASILISK_PLAGUE_TIME_BEFORE_STONE_FORM = 2
BASILISK_PLAGUE_THINK_INTERVAL = 0.5
BASILISK_PLAGUE_STONE_FORM_DUR = 2

KABUTO_SHIELD_DUR = 4
KABUTO_SHIELD_RESISTANCE = 0.95

LAVA_FORGE_DMG_PER_ATT = 2
LAVA_FORGE_DMG_PER_AGI = 2000
LAVA_FORGE_RADIUS = 240

SHIPYARD_SHIELD_COOLDOWN = 0.1
SHIPYARD_VEIL_MAX_STACKS = 4
SHIPYARD_VEIL_BAD_PER_STACK = 100
SHIPYARD_SHIELD_PRIMARY_ATT_AS_DMG =10

IRON_COLOSSUS_ATT_PER_STR = 10
IRON_COLOSSUS_AMR_PER_STR = 0.5
IRON_COLOSSUS_DMG_PER_ATT = 50
IRON_COLOSSUS_ATT_SPD = 120
IRON_COLOSSUS_ATT_RNG = 180

RUBY_DRAGON_TICK_INTERVAL = 0.2
RUBY_DRAGON_TICK_DURATION = 9
RUBY_DRAGON_TICK_DMG_PER_STR = 1500
RUBY_DRAGON_IMPACT_DMG_PER_STR = 5000
RUBY_DRAGON_DURATION = 15
RUBY_DRAGON_DISTANCE = 1300

SUPER_ASCENDENCY_ATK_RANGE = 800
SUPER_ASCENDENCY_ATK_PCT = 150
SUPER_ASCENDENCY_ATK_SPD = 300
SUPER_ASCENDENCY_MOVE_SPD = 200
SUPER_ASCENDENCY_PROJECTILE_SPEED = 500
SUPER_ASCENDENCY_SEARCH_RADIUS = 550
SUPER_ASCENDENCY_CD_RED = 0.05
SUPER_ASCENDENCY_TARGETS = 5
SUPER_ASCENDENCY_MIN_DURATION = 12

STORMCRACK_ATTACK_DAMAGE_MULT = 20
STORMCRACK_ATTR_DAMAGE_MULT = 200
STORMCRACK_STUN_DURATION_AMP = 35

WHITE_MAGE_RADIUS = 400
WHITE_MAGE_SHIELD_DURATION = 16
WHITE_MAGE_INT_TO_HEAL = 4
WHITE_MAGE_BAD_PER_INT = 0.1
WHITE_MAGE_INT_DIVISOR = 10

HYPER_VISOR_CHANCE = 20
HYPER_VISOR_ATTACK_TO_DMG = 40
HYPER_VISOR_BAT = 1.2
HYPER_VISOR_AGI_TO_ITEM_AMP = 0.3
HYPER_VISOR_AGI_DIVISOR = 10
HYPER_VISOR_AOE = 450

CENTAUR_HORNS_DAMAGE_CAP = 15
CENTAUR_HORNS_DEBUFF_DURATION = 1.5
CENTAUR_HORNS_SELF_DMG_TICKRATE = 0.03
CENTAUR_HORNS_SELF_DMG = 1

DEATH_WHISPER_SLOW = 100
DEATH_WHISPER_DAMAGE_AMP_PCT = 30
DEATH_WHISPER_DURATION = 5

CAP_OF_WILD_NATURE_CHANCE_ONE = 30
CAP_OF_WILD_NATURE_DURATION_ONE = 3
CAP_OF_WILD_NATURE_CHANCE_TWO = 30
CAP_OF_WILD_NATURE_DURATION_TWO = 3
CAP_OF_WILD_NATURE_DAMAGE_PER_ATTRIBUTES = 750

LUMA_BEAM_CHANCE = 70
LUMA_DAMAGE_AMP = 400
LUMA_VISION_DURATION = 4
LUMA_ELEMENT_CAP = 5000

ODIN_HELMET_CHANCE = 10
ODIN_HELMET_MULT = 7

MUGATO_SPELL_SILENCE_DUR = 4
MUGATO_ATTACK_SILENCE_DUR = 0.6
MUGATO_POST_MITI_PCT = 600

SWAMP_WITCH_HAT_INT_TO_DMG = 600
SWAMP_WITCH_HAT_POST_MITI = 15
SWAMP_WITCH_HAT_DURATION = 8
SWAMP_WITCH_HAT_MAX_STACKS = 10

TRICKSTER_MASK_RANGE = 380
TRICKSTER_MASK_ALL_DMG_MULT_MIN = 0.5
TRICKSTER_MASK_ALL_DMG_MULT_MAX = 2.5 
TRICKSTER_MASK_W_DMG_MULT_MIN = 0.1
TRICKSTER_MASK_W_DMG_MULT_MAX = 6

TYRIUS_HP_PER_STR = 10
TYRIUS_MANA_PER_STR = 4

CERULEAN_HIGHGUARD_MANA_INCREASE = 400
CERULEAN_HIGHGUARD_BAD = 2000

PHANTOM_SORCERER_BAD = 2500
PHANTOM_SORCERER_CD_INCREASE = 4

ARCANE_CASCADE_MANA_DRAIN = 0.02
ARCANE_CASCADE_TICKRATE = 0.5
ARCANE_CASCADE_RANGE = 750
ARCANE_CASCADE_DAMAGE = 8000
ARCANE_CASCADE_MAGIC_RESISTANCE_LOSS = 30

ADAMANTINE_SAMURAI_CHANCE = 40
ADAMANTINE_SAMURAI_CRIT = 600
ADAMANTINE_SAMURAI_BASE_ATTACK_PER_LVL = 4000

GLINT_OF_ONU_CHANCE = 35
GLINT_OF_ONU_BUFF_DUR = 0.8 
GLINT_OF_ONU_NUMBER_OF_BONUS_ATTACKS = 2 --this one is purely for tooltip because of code structure
GLINT_OF_ONU_AS_BONUS = 1200

ROKNAR_EMPEROR_TICKRATE = 0.25
ROKNAR_EMPEROR_HP_PCT = 12

DEMON_MASK_CHANCE = 15
DEMON_MASK_AMP = 15
DEMON_MASK_AOE = 450

CREST_OF_UMBRAL_SENTINEL_ARMOR_LOSS = 70
CREST_OF_UMBRAL_SENTINEL_POST_MITI_MAGIC = 3
CREST_OF_UMBRAL_SENTINEL_MAX_STACKS = 5
CREST_OF_UMBRAL_SENTINEL_DURATION = 10

CARBUNCLE_DAMAGE_AMP = 1000
CARBUNCLE_STUN_DUR = 3
CARBUNCLE_SHIELD_DUR_RELATIVE_PCT = 35
CARBUNCLE_SHIELD_DUR_MIN = 1
CARBUNCLE_ENEMY_IMMUNITY_DURATION = 3

GRITHAULT_CHANCE = 24

WRAITH_HUNTER_DAMAGE_CONVERSION_PCT = 3
WRAITH_HUNTER_BASE_ATTACK = 5
WRAITH_HUNTER_MANA_DRAIN_PCT = 2
WRAITH_HUNTER_W_BAD = 350

HOOD_OF_DEFILER_ARMOR_REDUCTION = 15
HOOD_OF_DEFILER_POST_MITI_PHYS = 25
HOOD_OF_DEFILER_POST_MITI_MAX_STACKS = 5
HOOD_OF_DEFILER_DURATION = 10
HOOD_OF_DEFILER_BONUS_ATTACK_DMG_PER_TARGET = 0.5
HOOD_OF_DEFILER_MAX_STACKS_BONUS_DMG = 100

EXCAVATOR_ITEM_AMP_PER_INT = 0.5
EXCAVATOR_INT_DIVISOR = 10

BLACK_MAGE_MAGIC_POST_MITI = 280
BLACK_MAGE_ITEM_DAMAGE_PENALTY = 80

AUTUMN_SLEEPER_RADIUS = 900
AUTUMN_SLEEPER_ROOT_DUR = 3
AUTUMN_SLEEPER_ROOT_DUR_IMMUNITY = 10
AUTUMN_SLEEPER_RADIUS_R = 1200
AUTUMN_SLEEPER_ROOT_DUR_R = 4

EYE_OF_SEASONS_INT_TO_STR_AGI = 0.35

SILENT_TEMPLAR_DURATION = 10
SILENT_TEMPLAR_AS = 240
SILENT_TEMPLAR_ATTACK_TO_DAMAGE = 60

WIND_DEITY_CROWN_ATTACK_LIMIT = 10
WIND_DEITY_CROWN_LIMIT_INTERVAL = 1
WIND_DEITY_CROWN_BONUS_DMG = 2
WIND_DEITY_CROWN_BONUS_DMG_DURATION = 30

WATER_DEITY_CROWN_DAMAGE_AMP = 100
WATER_DEITY_CROWN_MOVESPEED_SLOW_PCT = 60
WATER_DEITY_CROWN_MOVESPEED_SLOW_DURATION = 6
WATER_DEITY_CROWN_ELEMENT_CAP = 5000

FIRE_DEITY_CROWN_CHANCE = 20
FIRE_DEITY_CROWN_AMP = 250
FIRE_DEITY_CROWN_AOE = 240
FIRE_DEITY_CROWN_STUN_DURATION = 0.6
FIRE_DEITY_CROWN_ELEMENT_CAP = 5000

CRIMSON_SKULL_CAP_HP_PCT_TO_DAMAGE = 50
CRIMSON_SKULL_CAP_RADIUS = 260

HOOD_OF_LORDS_CD_RED = 1
HOOD_OF_LORDS_BONUS_RANGE = 140

IGNEOUS_CANINE_STUN_DURATION = 0.2
IGNEOUS_CANINE_MOVESPEED_SLOW = 15
IGNEOUS_CANINE_AS_SLOW = 60
IGNEOUS_CANINE_ATTACK_TO_DMG = 2
IGNEOUS_CANINE_LAVA_INTERVAL = 0.5
IGNEOUS_CANINE_AOE = 320
IGNEOUS_CANINE_LAVA_POOL_AOE = 320
IGNEOUS_CANINE_LAVA_POOL_DURATION = 6

BURNING_SPIRIT_ATTACK_TO_DAMAGE = 200
BURNING_SPIRIT_CD_RED = 0.5

TWISTED_MASK_OF_AHNQHIR_PURPLE_CD_RED_PCT = 40

TWISTED_MASK_OF_AHNQHIR_YELLOW_CD_RED = 1

TWISTED_MASK_OF_AHNQHIR_BLUE_CD_RED_PCT = 40

HOOD_OF_SEA_ORACLE_ARMOR_AND_DMG_DEBUFF_PCT = 5
HOOD_OF_SEA_ORACLE_MAX_STACKS = 15
HOOD_OF_SEA_ORACLE_POST_MITI = 500
HOOD_OF_SEA_ORACLE_DURATION = 8

DARK_REEF_SHARK_HELMET_PASSIVE_BONUS = 100
DARK_REEF_SHARK_HELMET_PASSIVE_DURATION = 30
DARK_REEF_SHARK_HELMET_NUMBER_OF_ATTACKS = 7
DARK_REEF_SHARK_HELMET_ACTIVE_BONUS = 1000
DARK_REEF_SHARK_HELMET_ACTIVE_DURATION = 1.5

HELM_OF_THE_MOUNTAIN_GIANT_PERCENT_HEALTH = 200
HELM_OF_THE_MOUNTAIN_GIANT_PERCENT_TRESHOLD = 80
HELM_OF_THE_MOUNTAIN_GIANT_PERCENT_DAMAGE_REDUCTION = 50

ORTHOK_W_CAST_STACKS = 1
ORTHOK_Q_E_CAST_STACKS = 5
ORTHOK_R_CAST_STACKS = 12
ORTHOK_STACK_BAD = 8
ORTHOK_STACK_DURATION = 10

KNIGHT_HAWK_MAX_MOVESPEED_LIMIT = 300
KNIGHT_HAWK_DR_ABOVE_DEFAULT_MAX = 90
KNIGHT_HAWK_MS_GAIN = 350
KNIGHT_HAWK_MS_BUFF_DURATION = 10

MAGISTRATE_HOOD_MAX_CHARGES = 8
MAGISTRATE_HOOD_REPLENISH_TIME = 1
MAGISTRATE_HOOD_AOE = 300
MAGISTRATE_HOOD_DAMAGE_AMP_PCT = 50

EMERALD_DOULI_DMG_ABSORB_PER_MANA = 5
EMERALD_DOULI_ABSORBED_DMG_PCT = 95
EMERALD_DOULI_MANA_THRESHOLD_PCT = 10

WRAITH_CROWN_EVASION_PCT = 100
WRAITH_CROWN_MAG_RES_PCT = 95
WRAITH_CROWN_DISJOINT_INTERVAL_SEC = 3
WRAITH_CROWN_BUFF_HP_TRESHOLD_PCT = 35