DRILL_CRUSHER_MAX_STACKS_COUNT = 10
DRILL_CRUSHER_POSTMITIGATION = 2
DRILL_CRUSHER_DURATION = 4

WINTERBLIGHT_SOULFIRE_STORM_STACKS = 30
WINTERBLIGHT_SOULFIRE_TICK_RATE = 1
WINTERBLIGHT_SOULFIRE_BURN_DURATION = 4