WINTERBLIGHT_MITHRIL_BASE_REWARD = 1000
WINTERBLIGHT_MITHRIL_BASE_REWARD_STONE = 1000

WINTERBLIGHT_MITHRIL_MULT_ELITE = 2
WINTERBLIGHT_MITHRIL_MULT_LEGEND = 5

WINTERBLIGHT_MITHRIL_MULT_ELITE_STONE = 3
WINTERBLIGHT_MITHRIL_MULT_LEGEND_STONE = 6

WINTERBLIGHT_MITHRIL_MULT_TIAMAT = 1.5
WINTERBLIGHT_MITHRIL_MULT_REALM_BR = 0.5

WINTERBLIGHT_MITHRIL_MULT_TIAMAT_PER_LVL = 0.09
WINTERBLIGHT_MITHRIL_MULT_REALM_BR_PER_LVL = 0.09

WINTERBLIGHT_MITHRIL_PUZZLE_BASE = 100
WINTERBLIGHT_MITHRIL_PUZZLE_NORMAL_MULT = 1.2
WINTERBLIGHT_MITHRIL_PUZZLE_ELITE_MULT = 1.6
WINTERBLIGHT_MITHRIL_PUZZLE_LEGEND_MULT = 2.4

WINTERBLIGHT_MITHRIL_PUZZLE_STATUE_1 = 200
WINTERBLIGHT_MITHRIL_PUZZLE_STATUE_2 = 90
WINTERBLIGHT_MITHRIL_PUZZLE_STATUE_3 = 50
WINTERBLIGHT_MITHRIL_PUZZLE_STATUE_4 = 35
WINTERBLIGHT_MITHRIL_PUZZLE_STATUE_5 = 30
WINTERBLIGHT_MITHRIL_PUZZLE_STATUE_6 = 25
WINTERBLIGHT_MITHRIL_PUZZLE_STATUE_7 = 20
WINTERBLIGHT_MITHRIL_PUZZLE_STATUE_8 = 8
WINTERBLIGHT_MITHRIL_PUZZLE_STATUE_MORE = 7

WINTERBLIGHT_MITHRIL_CASTLE_REWARD = 3000
WINTERBLIGHT_MITHRIL_CASTLE_REWARD_STONE = 2000

--reward_azalea = (BASE x DIFF)xPrP + (BASE_STONE x DIFF_STONE)x Stones
--reward_tiamat =  (BASE x DIFF x MULT + BASE x DIFF x MULT x TiamatLVL x PER_LVL)xPrP + (BASE_STONE x DIFF_STONE) x Stones